version: '3'

services:
    webapp:
        image: hinata_ads_webapp
        env_file:
            - .env
        build:
            context: ./
            dockerfile: prod.Dockerfile
        restart: unless-stopped
        networks:
            - hinata_web_ads_network

    # Add more containers below (nginx, postgres, etc.)

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
    hinata_web_ads_network:
        driver: bridge
