/* eslint-disable @typescript-eslint/no-explicit-any */

import { IProduct } from '@lib/domain/interfaces/i-product';

export const ProductsAuctionDummy: IProduct[] = [
    {
        id: 'clbxg3il536985p612l0w4ge13',
        name: 'Decorating the Christmas tree!',
        description:
            'In winter, you want snow, fairy tales and miracles.\r\nCollection of snowmen for a gift to loved ones at Christmas.\r\nDecorating the Christmas tree!',
        file: 'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/tokens/a48e5dbb-e331-470c-bc28-2baadbee6408-huge-mango-sugar.JPG',
        previewFile: null,
        minimizedImage:
            'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/tokens/e54ef333-b9be-4a46-9ae6-73d4b9605037-mini-jolly-thankful-arm',
        s3Key: 'tokens/a48e5dbb-e331-470c-bc28-2baadbee6408-huge-mango-sugar.JPG',
        previewS3Key: null,
        miniS3Key: 'tokens/e54ef333-b9be-4a46-9ae6-73d4b9605037-mini-jolly-thankful-arm',
        streamingId: null,
        slug: 'decorating-the-christmas-tree',
        currency: 'USD',
        hotChoice: false,
        tags: [],
        productStockId: 'clbxg3il536986p612l4l4u1bj',
        tagId: null,
        price: 220,
        status: 'APPROVED',
        remarks: '',
        disableDownload: false,
        soldout: false,
        published: true,
        deleted: false,
        created: new Date(),
        updated: new Date(),
        rights: [
            {
                id: 'clbxg3il536988p61296m4f8mq',
                name: 'R001',
                productId: 'clbxg3il536985p612l0w4ge13',
                created: new Date(),
                updated: new Date(),
            },
        ],
        categories: [
            {
                id: 'clbxg3il536991p612wovio51e',
                productId: 'clbxg3il536985p612l0w4ge13',
                categoryId: 'ckv7v4np21713hx12brcv057e',
                created: new Date(),
                updated: new Date(),
                Category: {
                    id: 'ckv7v4np21713hx12brcv057e',
                    name: 'Art',
                    created: new Date(),
                    updated: new Date(),
                },
            },
        ],
        tag: null,
        stock: {
            id: 'clbxg3il536986p612l4l4u1bj',
            stock: 1,
            lastNumber: 1,
            maxNumber: 1,
            created: new Date(),
            updated: new Date(),
        },
        views: {
            id: 'clbxg3ilw37004p6127b76of1f',
            views: 1,
            productId: 'clbxg3il536985p612l0w4ge13',
            created: new Date(),
            updated: new Date(),
        },
        thumbnails: [],
        collections: [
            {
                id: 'clbxg3kjh37026p612ngm3f1ti',
                productId: 'clbxg3il536985p612l0w4ge13',
                userId: 'claol3ims406132612ks0t1fkc7',
                tokenId: 'clbxg3kis37016p612l9nmqhpj',
                origin: true,
                created: new Date(),
                updated: new Date(),
                User: {
                    id: 'claol3ims406132612ks0t1fkc7',
                    email: 'lukina.artist@gmail.com',
                    sub: 'auth0|63796c049740d5ecb0c8cfd3',
                    emailVerified: null,
                    firstName: 'Elena',
                    lastName: 'Lukina',
                    nickname: 'J.Lu',
                    password: null,
                    phone: '+37129513247',
                    image: 'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/users/avatar/b1245a15-8605-4b7b-9dfc-ed40d2ea52eb-burly-orange-baby',
                    s3Key: 'users/avatar/b1245a15-8605-4b7b-9dfc-ed40d2ea52eb-burly-orange-baby',
                    biography:
                        'Art for me is not only a way of expression, but also a source of joy and love! \r\n\r\nJ.Lu is a prizewinning artist from Latvia whose paintings have been exhibited in solo and group shows internationally. Inspired by the beauty of nature, Lukina creates impressionist style landscapes, botanical works, animal portraits, and more in oil on canvas. Her work is characterized by great technical skill and conjure up a warmth and nostalgia through soft color palettes and smooth textures.',
                    gender: 'FEMALE',
                    birthdate: new Date(),
                    sns: [
                        {
                            url: 'https://www.singulart.com/en/artist/elena-lukina-8963',
                            name: 'website',
                        },
                        {
                            url: 'https://www.facebook.com/ArtElenaLukina/',
                            name: 'facebook',
                        },
                    ],
                    hazamaAddress: 'hMuABw4Y1buXQPaBURZYAsraQJrKZuPUib',
                    hazamaWallet: null,
                    hazamaOriginalDomain: null,
                    salt: '42bd99b0dd94348e4ae81b1b6156071e',
                    iv: '0c8c220ae4a9af48cf06193c7c0d8968',
                    encryptedWif:
                        '1d95c8094e914b8c058aff5c46323587c6a9ab1aa2ba767383422ff654b6ea67fe588746dfc59b1179efce4f1078bc7c07569bc4f49f512aa805c165f56b2137',
                    stripeCustomerId: null,
                    role: 'CREATOR',
                    avatar: 'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/users/avatar/b1245a15-8605-4b7b-9dfc-ed40d2ea52eb-burly-orange-baby',
                    slug: 'j-lu',
                    wpSlug: 'wp-51231ba1-5ff8-43a8-83c9-ca11a2f2a8fa',
                    deleted: false,
                    operator: false,
                    countryId: 'ckv7v4mtw0379hx129tdt8z83',
                    created: new Date(),
                    updated: new Date(),
                },
            },
        ],
        sponsors: [],
    },
    {
        id: 'clbxg0k5435806p612asuovd71',
        name: 'Snowman and bullfinches',
        description:
            'In winter, you want snow, fairy tales and miracles.\r\nCollection of snowmen for a gift to loved ones at Christmas.\r\nSnowman and bullfinches.',
        file: 'https://amatsuhi-prod-images.s3.amazonaws.com/tokens/98ba7c0a-3321-48d3-9b49-dc3b1be977a8-purring-hundreds-fountain.jpg',
        previewFile: null,
        minimizedImage:
            'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/tokens/fb3b265d-ceb2-4274-8b5a-f35f1a166993-mini-full-large-juice',
        s3Key: 'tokens/98ba7c0a-3321-48d3-9b49-dc3b1be977a8-purring-hundreds-fountain.jpg',
        previewS3Key: null,
        miniS3Key: 'tokens/fb3b265d-ceb2-4274-8b5a-f35f1a166993-mini-full-large-juice',
        streamingId: null,
        slug: 'snowman-and-bullfinches',
        currency: 'USD',
        hotChoice: false,
        tags: [],
        productStockId: 'clbxg0k5435807p612ekyroq5i',
        tagId: null,
        price: 220,
        status: 'APPROVED',
        remarks: '',
        disableDownload: false,
        soldout: false,
        published: true,
        deleted: false,
        created: new Date(),
        updated: new Date(),
        rights: [
            {
                id: 'clbxg0k5435809p612om56qwj0',
                name: 'R001',
                productId: 'clbxg0k5435806p612asuovd71',
                created: new Date(),
                updated: new Date(),
            },
        ],
        categories: [
            {
                id: 'clbxg0k5435812p612njx616h4',
                productId: 'clbxg0k5435806p612asuovd71',
                categoryId: 'ckv7v4np21713hx12brcv057e',
                created: new Date(),
                updated: new Date(),
                Category: {
                    id: 'ckv7v4np21713hx12brcv057e',
                    name: 'Art',
                    created: new Date(),
                    updated: new Date(),
                },
            },
        ],
        tag: null,
        stock: {
            id: 'clbxg0k5435807p612ekyroq5i',
            stock: 1,
            lastNumber: 1,
            maxNumber: 1,
            created: new Date(),
            updated: new Date(),
        },
        views: {
            id: 'clbxg0k5z35825p612bm7655um',
            views: 1,
            productId: 'clbxg0k5435806p612asuovd71',
            created: new Date(),
            updated: new Date(),
        },
        thumbnails: [],
        collections: [
            {
                id: 'clbxg0m4o35847p612w5jxe6qn',
                productId: 'clbxg0k5435806p612asuovd71',
                userId: 'claol3ims406132612ks0t1fkc7',
                tokenId: 'clbxg0m4135837p612psenzwaj',
                origin: true,
                created: new Date(),
                updated: new Date(),
                User: {
                    id: 'claol3ims406132612ks0t1fkc7',
                    email: 'lukina.artist@gmail.com',
                    sub: 'auth0|63796c049740d5ecb0c8cfd3',
                    emailVerified: null,
                    firstName: 'Elena',
                    lastName: 'Lukina',
                    nickname: 'J.Lu',
                    password: null,
                    phone: '+37129513247',
                    image: 'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/users/avatar/b1245a15-8605-4b7b-9dfc-ed40d2ea52eb-burly-orange-baby',
                    s3Key: 'users/avatar/b1245a15-8605-4b7b-9dfc-ed40d2ea52eb-burly-orange-baby',
                    biography:
                        'Art for me is not only a way of expression, but also a source of joy and love! \r\n\r\nJ.Lu is a prizewinning artist from Latvia whose paintings have been exhibited in solo and group shows internationally. Inspired by the beauty of nature, Lukina creates impressionist style landscapes, botanical works, animal portraits, and more in oil on canvas. Her work is characterized by great technical skill and conjure up a warmth and nostalgia through soft color palettes and smooth textures.',
                    gender: 'FEMALE',
                    birthdate: new Date(),
                    sns: [
                        {
                            url: 'https://www.singulart.com/en/artist/elena-lukina-8963',
                            name: 'website',
                        },
                        {
                            url: 'https://www.facebook.com/ArtElenaLukina/',
                            name: 'facebook',
                        },
                    ],
                    hazamaAddress: 'hMuABw4Y1buXQPaBURZYAsraQJrKZuPUib',
                    hazamaWallet: null,
                    hazamaOriginalDomain: null,
                    salt: '42bd99b0dd94348e4ae81b1b6156071e',
                    iv: '0c8c220ae4a9af48cf06193c7c0d8968',
                    encryptedWif:
                        '1d95c8094e914b8c058aff5c46323587c6a9ab1aa2ba767383422ff654b6ea67fe588746dfc59b1179efce4f1078bc7c07569bc4f49f512aa805c165f56b2137',
                    stripeCustomerId: null,
                    role: 'CREATOR',
                    avatar: 'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/users/avatar/b1245a15-8605-4b7b-9dfc-ed40d2ea52eb-burly-orange-baby',
                    slug: 'j-lu',
                    wpSlug: 'wp-51231ba1-5ff8-43a8-83c9-ca11a2f2a8fa',
                    deleted: false,
                    operator: false,
                    countryId: 'ckv7v4mtw0379hx129tdt8z83',
                    created: new Date(),
                    updated: new Date(),
                },
            },
        ],
        sponsors: [],
    },
    {
        id: 'clbvwbz71431081ou12kkh6b0v8',
        name: 'Golden Token',
        description:
            'Abstract artwork was done with gold patina (liquid gold) on black canvas.\r\nBinary numbers and parallel lines create an unusual abstract composition with a 3D effect.\r\n\r\nAnastasia Vasilyeva is a contemporary artist living in Switzerland who pushes her viewers into the world of scientific art. Since 2018, her paintings have been presented at exhibitions in Europe and the USA. She is a prize-winner of art competitions organized by Artbox Gallery (Miami Art Week, Wynwood, USA. Presented by Artbox Project MIAMI2.0. Semi-finalist).\r\n\r\nNow available as NFT only on HINATA-NFT.',
        file: 'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/tokens/0a1c8c6d-0640-4c8b-a876-37364816ddb7-gifted-rotten-train.jpg',
        previewFile: null,
        minimizedImage:
            'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/tokens/a4f6a6bb-31e7-4267-8202-77aad524822a-mini-bald-brief-potato',
        s3Key: 'tokens/0a1c8c6d-0640-4c8b-a876-37364816ddb7-gifted-rotten-train.jpg',
        previewS3Key: null,
        miniS3Key: 'tokens/a4f6a6bb-31e7-4267-8202-77aad524822a-mini-bald-brief-potato',
        streamingId: null,
        slug: 'anastasia-golden-token',
        currency: 'USD',
        hotChoice: true,
        tags: ['gold', 'binary', 'token', 'science', 'crypto', 'informatics'],
        productStockId: 'clbvwbz71431082ou12inbmyxrb',
        tagId: null,
        price: 300,
        status: 'APPROVED',
        remarks: '',
        disableDownload: false,
        soldout: false,
        published: true,
        deleted: false,
        created: new Date(),
        updated: new Date(),
        rights: [
            {
                id: 'clbvwbz71431084ou1208i8dcen',
                name: 'R001',
                productId: 'clbvwbz71431081ou12kkh6b0v8',
                created: new Date(),
                updated: new Date(),
            },
        ],
        categories: [
            {
                id: 'clbvwbz71431087ou1275b8n6hu',
                productId: 'clbvwbz71431081ou12kkh6b0v8',
                categoryId: 'ckv7v4np21713hx12brcv057e',
                created: new Date(),
                updated: new Date(),
                Category: {
                    id: 'ckv7v4np21713hx12brcv057e',
                    name: 'Art',
                    created: new Date(),
                    updated: new Date(),
                },
            },
        ],
        tag: null,
        stock: {
            id: 'clbvwbz71431082ou12inbmyxrb',
            stock: 1,
            lastNumber: 1,
            maxNumber: 1,
            created: new Date(),
            updated: new Date(),
        },
        views: {
            id: 'clbvwbz7x431112ou12cxwukxd9',
            views: 11,
            productId: 'clbvwbz71431081ou12kkh6b0v8',
            created: new Date(),
            updated: new Date(),
        },
        thumbnails: [
            {
                id: 'clbvwbz71431088ou12rqq0ai1b',
                url: 'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/products/thumbnails/4f4e0aa1-8a07-412e-a282-5a5a9d343809-purple-thankful-afternoon',
                s3Key: null,
                productId: 'clbvwbz71431081ou12kkh6b0v8',
                created: new Date(),
                updated: new Date(),
            },
            {
                id: 'clbvwbz71431089ou12m2popn7s',
                url: 'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/products/thumbnails/407b3696-b001-4249-9930-ad1a356a3d1b-happy-burly-yottabyte',
                s3Key: null,
                productId: 'clbvwbz71431081ou12kkh6b0v8',
                created: new Date(),
                updated: new Date(),
            },
            {
                id: 'clbvwbz71431090ou12nhyh7t0g',
                url: 'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/products/thumbnails/de0e2dca-1a1f-470e-9fed-8133662ccb5c-dead-short-hospital',
                s3Key: null,
                productId: 'clbvwbz71431081ou12kkh6b0v8',
                created: new Date(),
                updated: new Date(),
            },
        ],
        collections: [
            {
                id: 'clbvwc4v5431134ou12rywucjyh',
                productId: 'clbvwbz71431081ou12kkh6b0v8',
                userId: 'clbkpvemh921719qi2kk9sg6qog',
                tokenId: 'clbvwc4ui431124ou12gyw4l0am',
                origin: true,
                created: new Date(),
                updated: new Date(),
                User: {
                    id: 'clbkpvemh921719qi2kk9sg6qog',
                    email: 'anavasilyeva@gmail.com',
                    sub: 'auth0|6397119dffa0ee78c0940d3f',
                    emailVerified: null,
                    firstName: 'Vasilyeva',
                    lastName: 'Anastasia',
                    nickname: 'Anastasia Vasilyeva',
                    password: null,
                    phone: '0791292124',
                    image: 'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/users/avatar/ccb5186c-563c-436a-ba06-7a5dd93cbf7c-shallow-boring-ocean',
                    s3Key: 'users/avatar/ccb5186c-563c-436a-ba06-7a5dd93cbf7c-shallow-boring-ocean',
                    biography:
                        'Anastasia Vasilyeva was born in 1982 in St.Petersburg (Russia) where she grew up. In 2008 she moved to Switzerland where she\'s been living since then. \r\n\r\nAnastasia Vasilyeva is an artist dedicated to abstract conceptual art. In her works, she combines art with motifs and themes of mathematics as well as computer science. Her work also focuses on current social problems. Inspired by Mark Rothko, Jackson Pollack, Kandinsky, and Gerhard Richter, Anastasia Vasilyeva makes a conceptual contribution to Contemporary Art. \r\n\r\nBorn in an artist-family (4th generation) she learned the basic painting techniques from her father and continued to further develop them in various painting courses. Anastasia is also very interested in the history of art. The art exhibitions of classical and modern works of art always give her new inputs and inspirations for her work.\r\n\r\nSince 2016 Anastasia Vasilyeva has been exhibiting her works in certain art galleries, museums as well as in large IT and insurance companies in the USA, Switzerland, Germany, and Estonia.\r\n2021 - Exhibition in Darwin Museum in Moscow, The project EARTH2021;\r\n2019 -Selected as Semi-finalist in the project MIAMI2.0 organized by ARTBOX.Projects. "School board N8" was presented in Wynwood during Art Basel Miami Week.\r\n2018 -The diptych "Glacier" was owned by the MUSEUM OF ART in Narva, Estonia;  \r\n\r\n\r\nInfluences\r\nMark Rothko, Jackson Pollack, Kandinsky, Gerhard Richter, Kazimir Malevich\r\n\r\n\r\nEducation\r\n2021-2021 MoMa Courses, specialization Modern and Contemporary Art and Design New York, New York, United States \r\n2016-2017 Mix media contemporary artist Sempach, Switzerland \r\n1999-2004 Dip. Applied Mathematician St.Petersburg, Russia ',
                    gender: 'FEMALE',
                    birthdate: new Date(),
                    sns: [
                        {
                            url: 'https://www.youtube.com/@AnastasiaVasilyeva',
                            name: 'youtube',
                        },
                        {
                            url: 'https://www.anavasilyeva.com/collections?isHome=1',
                            name: 'website',
                        },
                        {
                            url: 'https://www.instagram.com/anastasiavasiljeva/',
                            name: 'instagram',
                        },
                        {
                            url: 'https://twitter.com/VasilyevaArt',
                            name: 'twitter',
                        },
                    ],
                    hazamaAddress: 'hKwpAGMe5ybTJVWTRLRTCgyt7HFaV8odii',
                    hazamaWallet: null,
                    hazamaOriginalDomain: null,
                    salt: '8e9b30935d6f504a4c169385c0c445aa',
                    iv: 'b8b95e5859cca4263a3c06f9399861da',
                    encryptedWif:
                        '690edaf11c11b1d544373c759ac5ae82a6d5d3bd525607a5c3c6a6c25c5e34979d6b340395af0cd0b814b8d525d7046ba2c53896ca07b10eb69f42d47f587fbb',
                    stripeCustomerId: null,
                    role: 'CREATOR',
                    avatar: 'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/users/avatar/ccb5186c-563c-436a-ba06-7a5dd93cbf7c-shallow-boring-ocean',
                    slug: 'anastasia-vasilyeva',
                    wpSlug: 'wp-88af923f-83fd-4aa1-8042-0d6bd08a5daf',
                    deleted: false,
                    operator: false,
                    countryId: 'ckv7v4n761052hx128tpnfswx',
                    created: new Date(),
                    updated: new Date(),
                },
            },
        ],
        sponsors: [],
    },
    {
        id: 'clbvw5wci430591ou12uf182np9',
        name: 'Encrypted connection from Science Art Collection',
        description:
            'The winner of the prize of the Biancoscuro Art Contest - the exhibition at Art Fair Innsbruck October 2022! Published in several issues of the art magazine -Biancoscuro.\r\nAbstract painting was done with acrylic and metal pigment colors on black canvas. \r\nBinary numbers and parallel lines create an unusual abstract composition with a 3D effect.\r\nNow available as NFT only on HINATA-NFT.\r\n\r\nAnastasia Vasilyeva is a contemporary artist living in Switzerland who pushes her viewers into the world of scientific art. Since 2018, her paintings have been presented at exhibitions in Europe and the USA. She is a prize-winner of art competitions organized by Artbox Gallery (Miami Art Week, Wynwood, USA. Presented by Artbox Project MIAMI2.0. Semi-finalist).\r\n',
        file: 'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/tokens/f0e03c7d-9272-4e0a-8ec0-5f3c0bda9b6f-wooden-obedient-dog.jpeg',
        previewFile: null,
        minimizedImage:
            'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/tokens/98badc66-f641-4bec-84a0-bbc9ee9a5872-mini-obnoxious-aggressive-pharmacist',
        s3Key: 'tokens/f0e03c7d-9272-4e0a-8ec0-5f3c0bda9b6f-wooden-obedient-dog.jpeg',
        previewS3Key: null,
        miniS3Key: 'tokens/98badc66-f641-4bec-84a0-bbc9ee9a5872-mini-obnoxious-aggressive-pharmacist',
        streamingId: null,
        slug: 'anastasia-encrypted-connections',
        currency: 'USD',
        hotChoice: false,
        tags: ['minimalist', 'black', 'lines', 'geometric', 'science'],
        productStockId: 'clbvw5wci430592ou129ngy11b3',
        tagId: null,
        price: 600,
        status: 'APPROVED',
        remarks: '',
        disableDownload: false,
        soldout: false,
        published: true,
        deleted: false,
        created: new Date(),
        updated: new Date(),
        rights: [
            {
                id: 'clbvw5wci430594ou12i29yg28d',
                name: 'R001',
                productId: 'clbvw5wci430591ou12uf182np9',
                created: new Date(),
                updated: new Date(),
            },
        ],
        categories: [
            {
                id: 'clbvw5wci430597ou12iz1qd4us',
                productId: 'clbvw5wci430591ou12uf182np9',
                categoryId: 'ckv7v4np21713hx12brcv057e',
                created: new Date(),
                updated: new Date(),
                Category: {
                    id: 'ckv7v4np21713hx12brcv057e',
                    name: 'Art',
                    created: new Date(),
                    updated: new Date(),
                },
            },
        ],
        tag: null,
        stock: {
            id: 'clbvw5wci430592ou129ngy11b3',
            stock: 1,
            lastNumber: 1,
            maxNumber: 1,
            created: new Date(),
            updated: new Date(),
        },
        views: {
            id: 'clbvw5wdb430610ou12kpeo6rio',
            views: 2,
            productId: 'clbvw5wci430591ou12uf182np9',
            created: new Date(),
            updated: new Date(),
        },
        thumbnails: [],
        collections: [
            {
                id: 'clbvw61so430694ou12v3g46n5e',
                productId: 'clbvw5wci430591ou12uf182np9',
                userId: 'clbkpvemh921719qi2kk9sg6qog',
                tokenId: 'clbvw61rn430684ou12q1ysuls0',
                origin: true,
                created: new Date(),
                updated: new Date(),
                User: {
                    id: 'clbkpvemh921719qi2kk9sg6qog',
                    email: 'anavasilyeva@gmail.com',
                    sub: 'auth0|6397119dffa0ee78c0940d3f',
                    emailVerified: null,
                    firstName: 'Vasilyeva',
                    lastName: 'Anastasia',
                    nickname: 'Anastasia Vasilyeva',
                    password: null,
                    phone: '0791292124',
                    image: 'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/users/avatar/ccb5186c-563c-436a-ba06-7a5dd93cbf7c-shallow-boring-ocean',
                    s3Key: 'users/avatar/ccb5186c-563c-436a-ba06-7a5dd93cbf7c-shallow-boring-ocean',
                    biography:
                        'Anastasia Vasilyeva was born in 1982 in St.Petersburg (Russia) where she grew up. In 2008 she moved to Switzerland where she\'s been living since then. \r\n\r\nAnastasia Vasilyeva is an artist dedicated to abstract conceptual art. In her works, she combines art with motifs and themes of mathematics as well as computer science. Her work also focuses on current social problems. Inspired by Mark Rothko, Jackson Pollack, Kandinsky, and Gerhard Richter, Anastasia Vasilyeva makes a conceptual contribution to Contemporary Art. \r\n\r\nBorn in an artist-family (4th generation) she learned the basic painting techniques from her father and continued to further develop them in various painting courses. Anastasia is also very interested in the history of art. The art exhibitions of classical and modern works of art always give her new inputs and inspirations for her work.\r\n\r\nSince 2016 Anastasia Vasilyeva has been exhibiting her works in certain art galleries, museums as well as in large IT and insurance companies in the USA, Switzerland, Germany, and Estonia.\r\n2021 - Exhibition in Darwin Museum in Moscow, The project EARTH2021;\r\n2019 -Selected as Semi-finalist in the project MIAMI2.0 organized by ARTBOX.Projects. "School board N8" was presented in Wynwood during Art Basel Miami Week.\r\n2018 -The diptych "Glacier" was owned by the MUSEUM OF ART in Narva, Estonia;  \r\n\r\n\r\nInfluences\r\nMark Rothko, Jackson Pollack, Kandinsky, Gerhard Richter, Kazimir Malevich\r\n\r\n\r\nEducation\r\n2021-2021 MoMa Courses, specialization Modern and Contemporary Art and Design New York, New York, United States \r\n2016-2017 Mix media contemporary artist Sempach, Switzerland \r\n1999-2004 Dip. Applied Mathematician St.Petersburg, Russia ',
                    gender: 'FEMALE',
                    birthdate: new Date(),
                    sns: [
                        {
                            url: 'https://www.youtube.com/@AnastasiaVasilyeva',
                            name: 'youtube',
                        },
                        {
                            url: 'https://www.anavasilyeva.com/collections?isHome=1',
                            name: 'website',
                        },
                        {
                            url: 'https://www.instagram.com/anastasiavasiljeva/',
                            name: 'instagram',
                        },
                        {
                            url: 'https://twitter.com/VasilyevaArt',
                            name: 'twitter',
                        },
                    ],
                    hazamaAddress: 'hKwpAGMe5ybTJVWTRLRTCgyt7HFaV8odii',
                    hazamaWallet: null,
                    hazamaOriginalDomain: null,
                    salt: '8e9b30935d6f504a4c169385c0c445aa',
                    iv: 'b8b95e5859cca4263a3c06f9399861da',
                    encryptedWif:
                        '690edaf11c11b1d544373c759ac5ae82a6d5d3bd525607a5c3c6a6c25c5e34979d6b340395af0cd0b814b8d525d7046ba2c53896ca07b10eb69f42d47f587fbb',
                    stripeCustomerId: null,
                    role: 'CREATOR',
                    avatar: 'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/users/avatar/ccb5186c-563c-436a-ba06-7a5dd93cbf7c-shallow-boring-ocean',
                    slug: 'anastasia-vasilyeva',
                    wpSlug: 'wp-88af923f-83fd-4aa1-8042-0d6bd08a5daf',
                    deleted: false,
                    operator: false,
                    countryId: 'ckv7v4n761052hx128tpnfswx',
                    created: new Date(),
                    updated: new Date(),
                },
            },
        ],
        sponsors: [],
    },
    {
        id: 'clbvw0kkp425025g72koyh9hv7a',
        name: 'ENIGMA from Science art collection',
        description:
            "Abstract artwork in the style of the old Schoolboard from the Science Art Collection by Anastasia Vasilyeva.\r\nThe original artworks from the Science-Art Collection have been presented in art galleries and art fairs in Europe - Spain, Italy, Germany, Switzerland, and Austria. The unique style that combines art and science is a highlight for any contemporary art exhibition. Some of Anastasia Vasilyeva's artworks are already in the collection of the Art Museum in Estonia (Narva City).\r\n",
        file: 'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/tokens/c2204827-a2c5-481b-a534-fe343daae2d2-orange-scruffy-rose.jpg',
        previewFile: null,
        minimizedImage:
            'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/tokens/1c06ae97-ac58-4e91-a080-25bff6ae5940-mini-vast-petite-stone',
        s3Key: 'tokens/c2204827-a2c5-481b-a534-fe343daae2d2-orange-scruffy-rose.jpg',
        previewS3Key: null,
        miniS3Key: 'tokens/1c06ae97-ac58-4e91-a080-25bff6ae5940-mini-vast-petite-stone',
        streamingId: null,
        slug: 'anastasia-enigma',
        currency: 'USD',
        hotChoice: false,
        tags: ['science art', 'anastasia vasilyeva art', 'mathematics', 'green'],
        productStockId: 'clbvw0kkp425026g72kahl3soj7',
        tagId: null,
        price: 800,
        status: 'APPROVED',
        remarks: '',
        disableDownload: false,
        soldout: false,
        published: true,
        deleted: false,
        created: new Date(),
        updated: new Date(),
        rights: [
            {
                id: 'clbvw0kkp425028g72kiy8w33wy',
                name: 'R001',
                productId: 'clbvw0kkp425025g72koyh9hv7a',
                created: new Date(),
                updated: new Date(),
            },
        ],
        categories: [
            {
                id: 'clbvw0kkp425031g72kuh5kmpcl',
                productId: 'clbvw0kkp425025g72koyh9hv7a',
                categoryId: 'ckv7v4np21713hx12brcv057e',
                created: new Date(),
                updated: new Date(),
                Category: {
                    id: 'ckv7v4np21713hx12brcv057e',
                    name: 'Art',
                    created: new Date(),
                    updated: new Date(),
                },
            },
        ],
        tag: null,
        stock: {
            id: 'clbvw0kkp425026g72kahl3soj7',
            stock: 1,
            lastNumber: 1,
            maxNumber: 1,
            created: new Date(),
            updated: new Date(),
        },
        views: {
            id: 'clbvw0kmi425052g72k1k0lewst',
            views: 4,
            productId: 'clbvw0kkp425025g72koyh9hv7a',
            created: new Date(),
            updated: new Date(),
        },
        thumbnails: [
            {
                id: 'clbvw0kkp425032g72keimsn9ez',
                url: 'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/products/thumbnails/a0acb23d-00b7-4cdb-a97b-bbb9ff5cebdf-dazzling-drab-hair',
                s3Key: null,
                productId: 'clbvw0kkp425025g72koyh9hv7a',
                created: new Date(),
                updated: new Date(),
            },
            {
                id: 'clbvw0kkp425033g72kypr8mhjt',
                url: 'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/products/thumbnails/1ff78e2e-5dcb-4d40-be8a-03aa9a356fd4-easy-nutritious-beach',
                s3Key: null,
                productId: 'clbvw0kkp425025g72koyh9hv7a',
                created: new Date(),
                updated: new Date(),
            },
        ],
        collections: [
            {
                id: 'clbvw0qhf425074g72k2e0qafjd',
                productId: 'clbvw0kkp425025g72koyh9hv7a',
                userId: 'clbkpvemh921719qi2kk9sg6qog',
                tokenId: 'clbvw0qgf425064g72kn8ig7dut',
                origin: true,
                created: new Date(),
                updated: new Date(),
                User: {
                    id: 'clbkpvemh921719qi2kk9sg6qog',
                    email: 'anavasilyeva@gmail.com',
                    sub: 'auth0|6397119dffa0ee78c0940d3f',
                    emailVerified: null,
                    firstName: 'Vasilyeva',
                    lastName: 'Anastasia',
                    nickname: 'Anastasia Vasilyeva',
                    password: null,
                    phone: '0791292124',
                    image: 'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/users/avatar/ccb5186c-563c-436a-ba06-7a5dd93cbf7c-shallow-boring-ocean',
                    s3Key: 'users/avatar/ccb5186c-563c-436a-ba06-7a5dd93cbf7c-shallow-boring-ocean',
                    biography:
                        'Anastasia Vasilyeva was born in 1982 in St.Petersburg (Russia) where she grew up. In 2008 she moved to Switzerland where she\'s been living since then. \r\n\r\nAnastasia Vasilyeva is an artist dedicated to abstract conceptual art. In her works, she combines art with motifs and themes of mathematics as well as computer science. Her work also focuses on current social problems. Inspired by Mark Rothko, Jackson Pollack, Kandinsky, and Gerhard Richter, Anastasia Vasilyeva makes a conceptual contribution to Contemporary Art. \r\n\r\nBorn in an artist-family (4th generation) she learned the basic painting techniques from her father and continued to further develop them in various painting courses. Anastasia is also very interested in the history of art. The art exhibitions of classical and modern works of art always give her new inputs and inspirations for her work.\r\n\r\nSince 2016 Anastasia Vasilyeva has been exhibiting her works in certain art galleries, museums as well as in large IT and insurance companies in the USA, Switzerland, Germany, and Estonia.\r\n2021 - Exhibition in Darwin Museum in Moscow, The project EARTH2021;\r\n2019 -Selected as Semi-finalist in the project MIAMI2.0 organized by ARTBOX.Projects. "School board N8" was presented in Wynwood during Art Basel Miami Week.\r\n2018 -The diptych "Glacier" was owned by the MUSEUM OF ART in Narva, Estonia;  \r\n\r\n\r\nInfluences\r\nMark Rothko, Jackson Pollack, Kandinsky, Gerhard Richter, Kazimir Malevich\r\n\r\n\r\nEducation\r\n2021-2021 MoMa Courses, specialization Modern and Contemporary Art and Design New York, New York, United States \r\n2016-2017 Mix media contemporary artist Sempach, Switzerland \r\n1999-2004 Dip. Applied Mathematician St.Petersburg, Russia ',
                    gender: 'FEMALE',
                    birthdate: new Date(),
                    sns: [
                        {
                            url: 'https://www.youtube.com/@AnastasiaVasilyeva',
                            name: 'youtube',
                        },
                        {
                            url: 'https://www.anavasilyeva.com/collections?isHome=1',
                            name: 'website',
                        },
                        {
                            url: 'https://www.instagram.com/anastasiavasiljeva/',
                            name: 'instagram',
                        },
                        {
                            url: 'https://twitter.com/VasilyevaArt',
                            name: 'twitter',
                        },
                    ],
                    hazamaAddress: 'hKwpAGMe5ybTJVWTRLRTCgyt7HFaV8odii',
                    hazamaWallet: null,
                    hazamaOriginalDomain: null,
                    salt: '8e9b30935d6f504a4c169385c0c445aa',
                    iv: 'b8b95e5859cca4263a3c06f9399861da',
                    encryptedWif:
                        '690edaf11c11b1d544373c759ac5ae82a6d5d3bd525607a5c3c6a6c25c5e34979d6b340395af0cd0b814b8d525d7046ba2c53896ca07b10eb69f42d47f587fbb',
                    stripeCustomerId: null,
                    role: 'CREATOR',
                    avatar: 'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/users/avatar/ccb5186c-563c-436a-ba06-7a5dd93cbf7c-shallow-boring-ocean',
                    slug: 'anastasia-vasilyeva',
                    wpSlug: 'wp-88af923f-83fd-4aa1-8042-0d6bd08a5daf',
                    deleted: false,
                    operator: false,
                    countryId: 'ckv7v4n761052hx128tpnfswx',
                    created: new Date(),
                    updated: new Date(),
                },
            },
        ],
        sponsors: [],
    },
    {
        id: 'clbvtcdmv420270g72k0gyne8bs',
        name: 'Winter sketch Path to the river',
        description:
            'This painting is inspired by one winter day.\r\nSnowy footpath to the river. A beautiful landscape that pleases the eye.\r\nAll colors of the winter palette.\r\nFrom warm oranges to cool blues and turquoises.\r\nPasty painting.',
        file: 'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/tokens/bd62fea4-ca58-4e95-9f18-a7285440b8bf-spicy-fancy-sunset.JPG',
        previewFile: null,
        minimizedImage:
            'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/tokens/5e3b6e28-85d7-4c43-b39f-c043d39398d4-mini-putrid-teeny-plumber',
        s3Key: 'tokens/bd62fea4-ca58-4e95-9f18-a7285440b8bf-spicy-fancy-sunset.JPG',
        previewS3Key: null,
        miniS3Key: 'tokens/5e3b6e28-85d7-4c43-b39f-c043d39398d4-mini-putrid-teeny-plumber',
        streamingId: null,
        slug: 'winter-sketch-path-to-the-river',
        currency: 'USD',
        hotChoice: true,
        tags: [],
        productStockId: 'clbvtcdmv420271g72kksctlrsn',
        tagId: null,
        price: 270,
        status: 'APPROVED',
        remarks: '',
        disableDownload: false,
        soldout: false,
        published: true,
        deleted: false,
        created: new Date(),
        updated: new Date(),
        rights: [
            {
                id: 'clbvtcdmv420273g72k8rirh8by',
                name: 'R001',
                productId: 'clbvtcdmv420270g72k0gyne8bs',
                created: new Date(),
                updated: new Date(),
            },
        ],
        categories: [
            {
                id: 'clbvtcdmv420276g72ksq6k0kmz',
                productId: 'clbvtcdmv420270g72k0gyne8bs',
                categoryId: 'ckv7v4np21713hx12brcv057e',
                created: new Date(),
                updated: new Date(),
                Category: {
                    id: 'ckv7v4np21713hx12brcv057e',
                    name: 'Art',
                    created: new Date(),
                    updated: new Date(),
                },
            },
        ],
        tag: null,
        stock: {
            id: 'clbvtcdmv420271g72kksctlrsn',
            stock: 1,
            lastNumber: 1,
            maxNumber: 1,
            created: new Date(),
            updated: new Date(),
        },
        views: {
            id: 'clbvtcdo3420289g72ke4z8fsb6',
            views: 9,
            productId: 'clbvtcdmv420270g72k0gyne8bs',
            created: new Date(),
            updated: new Date(),
        },
        thumbnails: [],
        collections: [
            {
                id: 'clbvtcjbd420311g72k686yfvda',
                productId: 'clbvtcdmv420270g72k0gyne8bs',
                userId: 'claol3ims406132612ks0t1fkc7',
                tokenId: 'clbvtcjac420301g72knhud1x36',
                origin: true,
                created: new Date(),
                updated: new Date(),
                User: {
                    id: 'claol3ims406132612ks0t1fkc7',
                    email: 'lukina.artist@gmail.com',
                    sub: 'auth0|63796c049740d5ecb0c8cfd3',
                    emailVerified: null,
                    firstName: 'Elena',
                    lastName: 'Lukina',
                    nickname: 'J.Lu',
                    password: null,
                    phone: '+37129513247',
                    image: 'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/users/avatar/b1245a15-8605-4b7b-9dfc-ed40d2ea52eb-burly-orange-baby',
                    s3Key: 'users/avatar/b1245a15-8605-4b7b-9dfc-ed40d2ea52eb-burly-orange-baby',
                    biography:
                        'Art for me is not only a way of expression, but also a source of joy and love! \r\n\r\nJ.Lu is a prizewinning artist from Latvia whose paintings have been exhibited in solo and group shows internationally. Inspired by the beauty of nature, Lukina creates impressionist style landscapes, botanical works, animal portraits, and more in oil on canvas. Her work is characterized by great technical skill and conjure up a warmth and nostalgia through soft color palettes and smooth textures.',
                    gender: 'FEMALE',
                    birthdate: new Date(),
                    sns: [
                        {
                            url: 'https://www.singulart.com/en/artist/elena-lukina-8963',
                            name: 'website',
                        },
                        {
                            url: 'https://www.facebook.com/ArtElenaLukina/',
                            name: 'facebook',
                        },
                    ],
                    hazamaAddress: 'hMuABw4Y1buXQPaBURZYAsraQJrKZuPUib',
                    hazamaWallet: null,
                    hazamaOriginalDomain: null,
                    salt: '42bd99b0dd94348e4ae81b1b6156071e',
                    iv: '0c8c220ae4a9af48cf06193c7c0d8968',
                    encryptedWif:
                        '1d95c8094e914b8c058aff5c46323587c6a9ab1aa2ba767383422ff654b6ea67fe588746dfc59b1179efce4f1078bc7c07569bc4f49f512aa805c165f56b2137',
                    stripeCustomerId: null,
                    role: 'CREATOR',
                    avatar: 'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/users/avatar/b1245a15-8605-4b7b-9dfc-ed40d2ea52eb-burly-orange-baby',
                    slug: 'j-lu',
                    wpSlug: 'wp-51231ba1-5ff8-43a8-83c9-ca11a2f2a8fa',
                    deleted: false,
                    operator: false,
                    countryId: 'ckv7v4mtw0379hx129tdt8z83',
                    created: new Date(),
                    updated: new Date(),
                },
            },
        ],
        sponsors: [],
    },
    {
        id: 'clbvt9yrn419499g72kfrrlhhqc',
        name: 'Snowman family',
        description:
            'In winter, you want snow, fairy tales and miracles.\r\nCollection of snowmen for a gift to loved ones at Christmas.',
        file: 'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/tokens/530acab4-4174-41cd-9a5b-82fd87c7bcdc-tight-mealy-continent.JPG',
        previewFile: null,
        minimizedImage:
            'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/tokens/b6774843-759b-4599-9710-5bd9927f156f-mini-fierce-boring-toothbrush',
        s3Key: 'tokens/530acab4-4174-41cd-9a5b-82fd87c7bcdc-tight-mealy-continent.JPG',
        previewS3Key: null,
        miniS3Key: 'tokens/b6774843-759b-4599-9710-5bd9927f156f-mini-fierce-boring-toothbrush',
        streamingId: null,
        slug: 'snowman-family',
        currency: 'USD',
        hotChoice: false,
        tags: [],
        productStockId: 'clbvt9yrn419500g72kaoyjgv70',
        tagId: null,
        price: 270,
        status: 'APPROVED',
        remarks: '',
        disableDownload: false,
        soldout: false,
        published: true,
        deleted: false,
        created: new Date(),
        updated: new Date(),
        rights: [
            {
                id: 'clbvt9yrn419502g72k12g85ox3',
                name: 'R001',
                productId: 'clbvt9yrn419499g72kfrrlhhqc',
                created: new Date(),
                updated: new Date(),
            },
        ],
        categories: [
            {
                id: 'clbvt9yrn419505g72kbea76ktj',
                productId: 'clbvt9yrn419499g72kfrrlhhqc',
                categoryId: 'ckv7v4np21713hx12brcv057e',
                created: new Date(),
                updated: new Date(),
                Category: {
                    id: 'ckv7v4np21713hx12brcv057e',
                    name: 'Art',
                    created: new Date(),
                    updated: new Date(),
                },
            },
        ],
        tag: null,
        stock: {
            id: 'clbvt9yrn419500g72kaoyjgv70',
            stock: 1,
            lastNumber: 1,
            maxNumber: 1,
            created: new Date(),
            updated: new Date(),
        },
        views: {
            id: 'clbvt9ysy419518g72kye8mnlyg',
            views: 7,
            productId: 'clbvt9yrn419499g72kfrrlhhqc',
            created: new Date(),
            updated: new Date(),
        },
        thumbnails: [],
        collections: [
            {
                id: 'clbvta4kn419564g72knrhctgsg',
                productId: 'clbvt9yrn419499g72kfrrlhhqc',
                userId: 'claol3ims406132612ks0t1fkc7',
                tokenId: 'clbvta4jn419554g72kis8l3vd6',
                origin: true,
                created: new Date(),
                updated: new Date(),
                User: {
                    id: 'claol3ims406132612ks0t1fkc7',
                    email: 'lukina.artist@gmail.com',
                    sub: 'auth0|63796c049740d5ecb0c8cfd3',
                    emailVerified: null,
                    firstName: 'Elena',
                    lastName: 'Lukina',
                    nickname: 'J.Lu',
                    password: null,
                    phone: '+37129513247',
                    image: 'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/users/avatar/b1245a15-8605-4b7b-9dfc-ed40d2ea52eb-burly-orange-baby',
                    s3Key: 'users/avatar/b1245a15-8605-4b7b-9dfc-ed40d2ea52eb-burly-orange-baby',
                    biography:
                        'Art for me is not only a way of expression, but also a source of joy and love! \r\n\r\nJ.Lu is a prizewinning artist from Latvia whose paintings have been exhibited in solo and group shows internationally. Inspired by the beauty of nature, Lukina creates impressionist style landscapes, botanical works, animal portraits, and more in oil on canvas. Her work is characterized by great technical skill and conjure up a warmth and nostalgia through soft color palettes and smooth textures.',
                    gender: 'FEMALE',
                    birthdate: new Date(),
                    sns: [
                        {
                            url: 'https://www.singulart.com/en/artist/elena-lukina-8963',
                            name: 'website',
                        },
                        {
                            url: 'https://www.facebook.com/ArtElenaLukina/',
                            name: 'facebook',
                        },
                    ],
                    hazamaAddress: 'hMuABw4Y1buXQPaBURZYAsraQJrKZuPUib',
                    hazamaWallet: null,
                    hazamaOriginalDomain: null,
                    salt: '42bd99b0dd94348e4ae81b1b6156071e',
                    iv: '0c8c220ae4a9af48cf06193c7c0d8968',
                    encryptedWif:
                        '1d95c8094e914b8c058aff5c46323587c6a9ab1aa2ba767383422ff654b6ea67fe588746dfc59b1179efce4f1078bc7c07569bc4f49f512aa805c165f56b2137',
                    stripeCustomerId: null,
                    role: 'CREATOR',
                    avatar: 'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/users/avatar/b1245a15-8605-4b7b-9dfc-ed40d2ea52eb-burly-orange-baby',
                    slug: 'j-lu',
                    wpSlug: 'wp-51231ba1-5ff8-43a8-83c9-ca11a2f2a8fa',
                    deleted: false,
                    operator: false,
                    countryId: 'ckv7v4mtw0379hx129tdt8z83',
                    created: new Date(),
                    updated: new Date(),
                },
            },
        ],
        sponsors: [],
    },
    {
        id: 'clbuvfzmz392568ou12o0vky4bf',
        name: 'Winter sketch',
        description:
            'There is a lot of snow outside the window.\r\nOn the branches of mountain ash bullfinches.\r\nWinter mood. Christmas is coming.\r\nThis painting is inspired by one winter day in December.\r\nSnow is everywhere.\r\nBunches of mountain ash are covered with snow and the birds are gathering fruits. Birds, Rowan, Snow. Italian canvas by Caravaggio.',
        file: 'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/tokens/540a0493-041e-4d99-bdfd-ad6da7e75f78-thankful-famous-hydrogen.JPG',
        previewFile: null,
        minimizedImage:
            'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/tokens/47e95a26-a6df-489f-a707-79a0f12d142c-mini-proud-witty-juice',
        s3Key: 'tokens/540a0493-041e-4d99-bdfd-ad6da7e75f78-thankful-famous-hydrogen.JPG',
        previewS3Key: null,
        miniS3Key: 'tokens/47e95a26-a6df-489f-a707-79a0f12d142c-mini-proud-witty-juice',
        streamingId: null,
        slug: 'winter-sketch',
        currency: 'USD',
        hotChoice: false,
        tags: [],
        productStockId: 'clbuvfzmz392569ou127n7zbwj4',
        tagId: null,
        price: 540,
        status: 'APPROVED',
        remarks: '',
        disableDownload: false,
        soldout: false,
        published: true,
        deleted: false,
        created: new Date(),
        updated: new Date(),
        rights: [
            {
                id: 'clbuvfzmz392571ou12w0a1q8ak',
                name: 'R001',
                productId: 'clbuvfzmz392568ou12o0vky4bf',
                created: new Date(),
                updated: new Date(),
            },
        ],
        categories: [
            {
                id: 'clbuvfzmz392574ou12j1x42t6o',
                productId: 'clbuvfzmz392568ou12o0vky4bf',
                categoryId: 'ckv7v4np21713hx12brcv057e',
                created: new Date(),
                updated: new Date(),
                Category: {
                    id: 'ckv7v4np21713hx12brcv057e',
                    name: 'Art',
                    created: new Date(),
                    updated: new Date(),
                },
            },
        ],
        tag: null,
        stock: {
            id: 'clbuvfzmz392569ou127n7zbwj4',
            stock: 1,
            lastNumber: 1,
            maxNumber: 1,
            created: new Date(),
            updated: new Date(),
        },
        views: {
            id: 'clbuvfznv392587ou12cfskz8gi',
            views: 4,
            productId: 'clbuvfzmz392568ou12o0vky4bf',
            created: new Date(),
            updated: new Date(),
        },
        thumbnails: [],
        collections: [
            {
                id: 'clbuvg498392626ou12auzl4z26',
                productId: 'clbuvfzmz392568ou12o0vky4bf',
                userId: 'claol3ims406132612ks0t1fkc7',
                tokenId: 'clbuvg48k392616ou12x9qytwom',
                origin: true,
                created: new Date(),
                updated: new Date(),
                User: {
                    id: 'claol3ims406132612ks0t1fkc7',
                    email: 'lukina.artist@gmail.com',
                    sub: 'auth0|63796c049740d5ecb0c8cfd3',
                    emailVerified: null,
                    firstName: 'Elena',
                    lastName: 'Lukina',
                    nickname: 'J.Lu',
                    password: null,
                    phone: '+37129513247',
                    image: 'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/users/avatar/b1245a15-8605-4b7b-9dfc-ed40d2ea52eb-burly-orange-baby',
                    s3Key: 'users/avatar/b1245a15-8605-4b7b-9dfc-ed40d2ea52eb-burly-orange-baby',
                    biography:
                        'Art for me is not only a way of expression, but also a source of joy and love! \r\n\r\nJ.Lu is a prizewinning artist from Latvia whose paintings have been exhibited in solo and group shows internationally. Inspired by the beauty of nature, Lukina creates impressionist style landscapes, botanical works, animal portraits, and more in oil on canvas. Her work is characterized by great technical skill and conjure up a warmth and nostalgia through soft color palettes and smooth textures.',
                    gender: 'FEMALE',
                    birthdate: new Date(),
                    sns: [
                        {
                            url: 'https://www.singulart.com/en/artist/elena-lukina-8963',
                            name: 'website',
                        },
                        {
                            url: 'https://www.facebook.com/ArtElenaLukina/',
                            name: 'facebook',
                        },
                    ],
                    hazamaAddress: 'hMuABw4Y1buXQPaBURZYAsraQJrKZuPUib',
                    hazamaWallet: null,
                    hazamaOriginalDomain: null,
                    salt: '42bd99b0dd94348e4ae81b1b6156071e',
                    iv: '0c8c220ae4a9af48cf06193c7c0d8968',
                    encryptedWif:
                        '1d95c8094e914b8c058aff5c46323587c6a9ab1aa2ba767383422ff654b6ea67fe588746dfc59b1179efce4f1078bc7c07569bc4f49f512aa805c165f56b2137',
                    stripeCustomerId: null,
                    role: 'CREATOR',
                    avatar: 'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/users/avatar/b1245a15-8605-4b7b-9dfc-ed40d2ea52eb-burly-orange-baby',
                    slug: 'j-lu',
                    wpSlug: 'wp-51231ba1-5ff8-43a8-83c9-ca11a2f2a8fa',
                    deleted: false,
                    operator: false,
                    countryId: 'ckv7v4mtw0379hx129tdt8z83',
                    created: new Date(),
                    updated: new Date(),
                },
            },
        ],
        sponsors: [],
    },
    {
        id: 'clbu0gw0m331997g72kasvmb19y',
        name: 'Outumn vibes',
        description: null,
        file: 'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/tokens/f8a2be8d-8679-4a1f-8a17-abdb300fe041-mango-clean-river.jpg',
        previewFile: null,
        minimizedImage:
            'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/tokens/91f9f31b-235b-4b62-b6cc-ba143e757322-mini-teeny-cold-flower',
        s3Key: 'tokens/f8a2be8d-8679-4a1f-8a17-abdb300fe041-mango-clean-river.jpg',
        previewS3Key: null,
        miniS3Key: 'tokens/91f9f31b-235b-4b62-b6cc-ba143e757322-mini-teeny-cold-flower',
        streamingId: null,
        slug: 'outumn-vibes-333',
        currency: 'USD',
        hotChoice: true,
        tags: [],
        productStockId: 'clbu0gw0n331998g72klytk81o5',
        tagId: null,
        price: 200,
        status: 'APPROVED',
        remarks: '',
        disableDownload: false,
        soldout: false,
        published: true,
        deleted: false,
        created: new Date(),
        updated: new Date(),
        rights: [
            {
                id: 'clbu0gw0n332000g72koeqeu5ie',
                name: 'R001',
                productId: 'clbu0gw0m331997g72kasvmb19y',
                created: new Date(),
                updated: new Date(),
            },
        ],
        categories: [
            {
                id: 'clbu0gw0n332003g72kyh43t8mn',
                productId: 'clbu0gw0m331997g72kasvmb19y',
                categoryId: 'ckv7v4np21713hx12brcv057e',
                created: new Date(),
                updated: new Date(),
                Category: {
                    id: 'ckv7v4np21713hx12brcv057e',
                    name: 'Art',
                    created: new Date(),
                    updated: new Date(),
                },
            },
        ],
        tag: null,
        stock: {
            id: 'clbu0gw0n331998g72klytk81o5',
            stock: 1,
            lastNumber: 1,
            maxNumber: 1,
            created: new Date(),
            updated: new Date(),
        },
        views: {
            id: 'clbu0gw34332024g72kwshzbeur',
            views: 10,
            productId: 'clbu0gw0m331997g72kasvmb19y',
            created: new Date(),
            updated: new Date(),
        },
        thumbnails: [
            {
                id: 'clbu0gw0n332004g72kdbfe3kk0',
                url: 'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/products/thumbnails/efad364c-8ac9-44dc-9cf5-c7f1ff47b840-putrid-loud-fountain',
                s3Key: null,
                productId: 'clbu0gw0m331997g72kasvmb19y',
                created: new Date(),
                updated: new Date(),
            },
            {
                id: 'clbu0gw0n332005g72krz1zsxvn',
                url: 'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/products/thumbnails/521313f2-22cf-496a-bdc5-1b126690cb70-hot-mysterious-lunch',
                s3Key: null,
                productId: 'clbu0gw0m331997g72kasvmb19y',
                created: new Date(),
                updated: new Date(),
            },
        ],
        collections: [
            {
                id: 'clbu0h060332046g72k8g0s5nal',
                productId: 'clbu0gw0m331997g72kasvmb19y',
                userId: 'clbsq8w76311124ou12qnyl6zyv',
                tokenId: 'clbu0h050332036g72klgzai1ez',
                origin: true,
                created: new Date(),
                updated: new Date(),
                User: {
                    id: 'clbsq8w76311124ou12qnyl6zyv',
                    email: 'maria.matveyeva.art@gmail.com',
                    sub: 'auth0|639e75a475fc227f53b000bb',
                    emailVerified: null,
                    firstName: 'Maria (Marija)',
                    lastName: 'Matveyeva (Matvejeva)',
                    nickname: 'Maria Matveyeva',
                    password: null,
                    phone: '+371 27105425',
                    image: 'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/users/avatar/c8255a98-1795-408b-88cb-06620204455f-ambitious-puny-ice',
                    s3Key: 'users/avatar/c8255a98-1795-408b-88cb-06620204455f-ambitious-puny-ice',
                    biography:
                        'I believe that the world already is full of trouble and of things that trigger negative emotions, so art should be full of light and positivity, it should inspire the person who looks at it, it should catch the viewer’s fantasy, it should emanate goodness.\r\n\r\nI believe that an artist, like a musician, can change the viewer’s mood to make it better.\r\n\r\nI love people and nature. I love painting them, love the play of light and darkness, and the lively playing of colors.\r\n\r\nMostly I paint using oil colors and watercolor. After learning the technique for painting icons, I fell in love with painting in layers.\r\n\r\nWorking in oil, I like to combine transparency with applying paint in dense brush strokes. This enables me to create depth and softness, to create a new dimension.',
                    gender: 'FEMALE',
                    birthdate: new Date(),
                    sns: [
                        {
                            url: 'https://www.instagram.com/maria.matveyeva.art/',
                            name: 'instagram',
                        },
                        {
                            url: 'https://www.facebook.com/maria.matveyeva.art',
                            name: 'facebook',
                        },
                        {
                            url: 'https://www.tricera.net/ja/artist/painters/8107665',
                            name: 'website',
                        },
                    ],
                    hazamaAddress: 'hcMrm7HLLwGKZuWscGRgZ73XVBLJUyU47r',
                    hazamaWallet: null,
                    hazamaOriginalDomain: null,
                    salt: '1a1c7aee11fef22063aeca2ff087a40a',
                    iv: '57b780d069aba908c6ebdfde50d35d4a',
                    encryptedWif:
                        '8c85067116ddf1648cb63a5e01c191e1e874d8f8807d0eb6e479886ee204e4ae5bae1e64d46be01155d6080cb563b8da6659df33c0d2f111d320d00ed9ca5676',
                    stripeCustomerId: null,
                    role: 'CREATOR',
                    avatar: 'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/users/avatar/c8255a98-1795-408b-88cb-06620204455f-ambitious-puny-ice',
                    slug: 'maria-matveyeva',
                    wpSlug: 'wp-8ab039da-059f-41f6-9534-1887f071f22c',
                    deleted: false,
                    operator: false,
                    countryId: 'ckv7v4mtw0379hx129tdt8z83',
                    created: new Date(),
                    updated: new Date(),
                },
            },
        ],
        sponsors: [],
    },
    {
        id: 'clbu02rg1331586g72ks9gawo3s',
        name: 'Chemistry Lab',
        description: 'The original artwork was painted from nature.',
        file: 'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/tokens/06c8e55c-841f-4d9f-9695-62e1d8bbf4a8-brief-acidic-potato.jpg',
        previewFile: null,
        minimizedImage:
            'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/tokens/ff1ded4c-ce58-4cdd-ab64-f63044ae1156-mini-dry-orange-lunch',
        s3Key: 'tokens/06c8e55c-841f-4d9f-9695-62e1d8bbf4a8-brief-acidic-potato.jpg',
        previewS3Key: null,
        miniS3Key: 'tokens/ff1ded4c-ce58-4cdd-ab64-f63044ae1156-mini-dry-orange-lunch',
        streamingId: null,
        slug: 'chemistry-lab-777',
        currency: 'USD',
        hotChoice: false,
        tags: [],
        productStockId: 'clbu02rg1331587g72k7duyc9al',
        tagId: null,
        price: 200,
        status: 'APPROVED',
        remarks: '',
        disableDownload: false,
        soldout: false,
        published: true,
        deleted: false,
        created: new Date(),
        updated: new Date(),
        rights: [
            {
                id: 'clbu02rg1331589g72knw84ewd2',
                name: 'R001',
                productId: 'clbu02rg1331586g72ks9gawo3s',
                created: new Date(),
                updated: new Date(),
            },
        ],
        categories: [
            {
                id: 'clbu02rg1331592g72kocogg1ob',
                productId: 'clbu02rg1331586g72ks9gawo3s',
                categoryId: 'ckv7v4np21713hx12brcv057e',
                created: new Date(),
                updated: new Date(),
                Category: {
                    id: 'ckv7v4np21713hx12brcv057e',
                    name: 'Art',
                    created: new Date(),
                    updated: new Date(),
                },
            },
        ],
        tag: null,
        stock: {
            id: 'clbu02rg1331587g72k7duyc9al',
            stock: 1,
            lastNumber: 1,
            maxNumber: 1,
            created: new Date(),
            updated: new Date(),
        },
        views: {
            id: 'clbu02rhe331609g72kfgxatwri',
            views: 3,
            productId: 'clbu02rg1331586g72ks9gawo3s',
            created: new Date(),
            updated: new Date(),
        },
        thumbnails: [
            {
                id: 'clbu02rg1331593g72k0jmb6qg1',
                url: 'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/products/thumbnails/f5d1c429-5387-41d9-bccd-edd82bbd2caa-swift-weak-jordan',
                s3Key: null,
                productId: 'clbu02rg1331586g72ks9gawo3s',
                created: new Date(),
                updated: new Date(),
            },
        ],
        collections: [
            {
                id: 'clbu02vo9331631g72koebfv6ce',
                productId: 'clbu02rg1331586g72ks9gawo3s',
                userId: 'clbsq8w76311124ou12qnyl6zyv',
                tokenId: 'clbu02vn9331621g72k4y5oor72',
                origin: true,
                created: new Date(),
                updated: new Date(),
                User: {
                    id: 'clbsq8w76311124ou12qnyl6zyv',
                    email: 'maria.matveyeva.art@gmail.com',
                    sub: 'auth0|639e75a475fc227f53b000bb',
                    emailVerified: null,
                    firstName: 'Maria (Marija)',
                    lastName: 'Matveyeva (Matvejeva)',
                    nickname: 'Maria Matveyeva',
                    password: null,
                    phone: '+371 27105425',
                    image: 'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/users/avatar/c8255a98-1795-408b-88cb-06620204455f-ambitious-puny-ice',
                    s3Key: 'users/avatar/c8255a98-1795-408b-88cb-06620204455f-ambitious-puny-ice',
                    biography:
                        'I believe that the world already is full of trouble and of things that trigger negative emotions, so art should be full of light and positivity, it should inspire the person who looks at it, it should catch the viewer’s fantasy, it should emanate goodness.\r\n\r\nI believe that an artist, like a musician, can change the viewer’s mood to make it better.\r\n\r\nI love people and nature. I love painting them, love the play of light and darkness, and the lively playing of colors.\r\n\r\nMostly I paint using oil colors and watercolor. After learning the technique for painting icons, I fell in love with painting in layers.\r\n\r\nWorking in oil, I like to combine transparency with applying paint in dense brush strokes. This enables me to create depth and softness, to create a new dimension.',
                    gender: 'FEMALE',
                    birthdate: new Date(),
                    sns: [
                        {
                            url: 'https://www.instagram.com/maria.matveyeva.art/',
                            name: 'instagram',
                        },
                        {
                            url: 'https://www.facebook.com/maria.matveyeva.art',
                            name: 'facebook',
                        },
                        {
                            url: 'https://www.tricera.net/ja/artist/painters/8107665',
                            name: 'website',
                        },
                    ],
                    hazamaAddress: 'hcMrm7HLLwGKZuWscGRgZ73XVBLJUyU47r',
                    hazamaWallet: null,
                    hazamaOriginalDomain: null,
                    salt: '1a1c7aee11fef22063aeca2ff087a40a',
                    iv: '57b780d069aba908c6ebdfde50d35d4a',
                    encryptedWif:
                        '8c85067116ddf1648cb63a5e01c191e1e874d8f8807d0eb6e479886ee204e4ae5bae1e64d46be01155d6080cb563b8da6659df33c0d2f111d320d00ed9ca5676',
                    stripeCustomerId: null,
                    role: 'CREATOR',
                    avatar: 'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/users/avatar/c8255a98-1795-408b-88cb-06620204455f-ambitious-puny-ice',
                    slug: 'maria-matveyeva',
                    wpSlug: 'wp-8ab039da-059f-41f6-9534-1887f071f22c',
                    deleted: false,
                    operator: false,
                    countryId: 'ckv7v4mtw0379hx129tdt8z83',
                    created: new Date(),
                    updated: new Date(),
                },
            },
        ],
        sponsors: [],
    },
    {
        id: 'clbtzpsfr335810ou12j1v9nj09',
        name: 'Lilly',
        description: 'This is one of my favorite artworks painted from nature. ',
        file: 'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/tokens/4960279e-1d9a-4f40-8088-0013178c6f92-tart-enough-lifeguard.jpg',
        previewFile: null,
        minimizedImage:
            'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/tokens/152b1604-7f80-41a7-815e-2de5219353a8-mini-great-agreeable-answer',
        s3Key: 'tokens/4960279e-1d9a-4f40-8088-0013178c6f92-tart-enough-lifeguard.jpg',
        previewS3Key: null,
        miniS3Key: 'tokens/152b1604-7f80-41a7-815e-2de5219353a8-mini-great-agreeable-answer',
        streamingId: null,
        slug: 'lovely-lilly',
        currency: 'USD',
        hotChoice: false,
        tags: [],
        productStockId: 'clbtzpsfr335811ou12ucfohuhv',
        tagId: null,
        price: 300,
        status: 'APPROVED',
        remarks: '',
        disableDownload: false,
        soldout: false,
        published: true,
        deleted: false,
        created: new Date(),
        updated: new Date(),
        rights: [
            {
                id: 'clbtzpsfs335813ou127nct83lt',
                name: 'R001',
                productId: 'clbtzpsfr335810ou12j1v9nj09',
                created: new Date(),
                updated: new Date(),
            },
        ],
        categories: [
            {
                id: 'clbtzpsfs335816ou12mxjlqmyw',
                productId: 'clbtzpsfr335810ou12j1v9nj09',
                categoryId: 'ckv7v4np21713hx12brcv057e',
                created: new Date(),
                updated: new Date(),
                Category: {
                    id: 'ckv7v4np21713hx12brcv057e',
                    name: 'Art',
                    created: new Date(),
                    updated: new Date(),
                },
            },
        ],
        tag: null,
        stock: {
            id: 'clbtzpsfr335811ou12ucfohuhv',
            stock: 1,
            lastNumber: 1,
            maxNumber: 1,
            created: new Date(),
            updated: new Date(),
        },
        views: {
            id: 'clbtzpsgj335837ou12dmjwv7vc',
            views: 5,
            productId: 'clbtzpsfr335810ou12j1v9nj09',
            created: new Date(),
            updated: new Date(),
        },
        thumbnails: [
            {
                id: 'clbtzpsfs335817ou127x1rr23i',
                url: 'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/products/thumbnails/3ff2fd29-7a8e-44c7-9a43-3b0cc4cc70f0-attractive-polite-sweden',
                s3Key: null,
                productId: 'clbtzpsfr335810ou12j1v9nj09',
                created: new Date(),
                updated: new Date(),
            },
            {
                id: 'clbtzpsfs335818ou127c0qddml',
                url: 'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/products/thumbnails/fee3e3af-af6c-494f-9f74-0e1e1c225fab-long-warm-lawyer',
                s3Key: null,
                productId: 'clbtzpsfr335810ou12j1v9nj09',
                created: new Date(),
                updated: new Date(),
            },
        ],
        collections: [
            {
                id: 'clbtzpwhf335859ou12oo2662wj',
                productId: 'clbtzpsfr335810ou12j1v9nj09',
                userId: 'clbsq8w76311124ou12qnyl6zyv',
                tokenId: 'clbtzpwgt335849ou12iymzu9j2',
                origin: true,
                created: new Date(),
                updated: new Date(),
                User: {
                    id: 'clbsq8w76311124ou12qnyl6zyv',
                    email: 'maria.matveyeva.art@gmail.com',
                    sub: 'auth0|639e75a475fc227f53b000bb',
                    emailVerified: null,
                    firstName: 'Maria (Marija)',
                    lastName: 'Matveyeva (Matvejeva)',
                    nickname: 'Maria Matveyeva',
                    password: null,
                    phone: '+371 27105425',
                    image: 'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/users/avatar/c8255a98-1795-408b-88cb-06620204455f-ambitious-puny-ice',
                    s3Key: 'users/avatar/c8255a98-1795-408b-88cb-06620204455f-ambitious-puny-ice',
                    biography:
                        'I believe that the world already is full of trouble and of things that trigger negative emotions, so art should be full of light and positivity, it should inspire the person who looks at it, it should catch the viewer’s fantasy, it should emanate goodness.\r\n\r\nI believe that an artist, like a musician, can change the viewer’s mood to make it better.\r\n\r\nI love people and nature. I love painting them, love the play of light and darkness, and the lively playing of colors.\r\n\r\nMostly I paint using oil colors and watercolor. After learning the technique for painting icons, I fell in love with painting in layers.\r\n\r\nWorking in oil, I like to combine transparency with applying paint in dense brush strokes. This enables me to create depth and softness, to create a new dimension.',
                    gender: 'FEMALE',
                    birthdate: new Date(),
                    sns: [
                        {
                            url: 'https://www.instagram.com/maria.matveyeva.art/',
                            name: 'instagram',
                        },
                        {
                            url: 'https://www.facebook.com/maria.matveyeva.art',
                            name: 'facebook',
                        },
                        {
                            url: 'https://www.tricera.net/ja/artist/painters/8107665',
                            name: 'website',
                        },
                    ],
                    hazamaAddress: 'hcMrm7HLLwGKZuWscGRgZ73XVBLJUyU47r',
                    hazamaWallet: null,
                    hazamaOriginalDomain: null,
                    salt: '1a1c7aee11fef22063aeca2ff087a40a',
                    iv: '57b780d069aba908c6ebdfde50d35d4a',
                    encryptedWif:
                        '8c85067116ddf1648cb63a5e01c191e1e874d8f8807d0eb6e479886ee204e4ae5bae1e64d46be01155d6080cb563b8da6659df33c0d2f111d320d00ed9ca5676',
                    stripeCustomerId: null,
                    role: 'CREATOR',
                    avatar: 'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/users/avatar/c8255a98-1795-408b-88cb-06620204455f-ambitious-puny-ice',
                    slug: 'maria-matveyeva',
                    wpSlug: 'wp-8ab039da-059f-41f6-9534-1887f071f22c',
                    deleted: false,
                    operator: false,
                    countryId: 'ckv7v4mtw0379hx129tdt8z83',
                    created: new Date(),
                    updated: new Date(),
                },
            },
        ],
        sponsors: [],
    },
    {
        id: 'clbtzf2ot335166ou12lclayh8p',
        name: 'Tender innocence',
        description: null,
        file: 'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/tokens/f55fa590-f95b-4373-baa3-fe45eb8f1161-white-putrid-city.jpg',
        previewFile: null,
        minimizedImage:
            'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/tokens/4a63b23b-367e-4083-985b-8657200a71b5-mini-damaged-wooden-beach',
        s3Key: 'tokens/f55fa590-f95b-4373-baa3-fe45eb8f1161-white-putrid-city.jpg',
        previewS3Key: null,
        miniS3Key: 'tokens/4a63b23b-367e-4083-985b-8657200a71b5-mini-damaged-wooden-beach',
        streamingId: null,
        slug: 'tender-innocence',
        currency: 'USD',
        hotChoice: false,
        tags: [],
        productStockId: 'clbtzf2ot335167ou129slg3wfe',
        tagId: null,
        price: 200,
        status: 'APPROVED',
        remarks: '',
        disableDownload: false,
        soldout: false,
        published: true,
        deleted: false,
        created: new Date(),
        updated: new Date(),
        rights: [
            {
                id: 'clbtzf2ou335169ou12c1bduzgx',
                name: 'R001',
                productId: 'clbtzf2ot335166ou12lclayh8p',
                created: new Date(),
                updated: new Date(),
            },
        ],
        categories: [
            {
                id: 'clbtzf2ou335172ou12we3nhcix',
                productId: 'clbtzf2ot335166ou12lclayh8p',
                categoryId: 'ckv7v4np21713hx12brcv057e',
                created: new Date(),
                updated: new Date(),
                Category: {
                    id: 'ckv7v4np21713hx12brcv057e',
                    name: 'Art',
                    created: new Date(),
                    updated: new Date(),
                },
            },
        ],
        tag: null,
        stock: {
            id: 'clbtzf2ot335167ou129slg3wfe',
            stock: 1,
            lastNumber: 1,
            maxNumber: 1,
            created: new Date(),
            updated: new Date(),
        },
        views: {
            id: 'clbtzf2pu335201ou12n2qwwf5d',
            views: 2,
            productId: 'clbtzf2ot335166ou12lclayh8p',
            created: new Date(),
            updated: new Date(),
        },
        thumbnails: [
            {
                id: 'clbtzf2ou335173ou12jl1tkm6a',
                url: 'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/products/thumbnails/f8607f80-778a-4ca4-8132-43ac6032cf90-puny-early-addition',
                s3Key: null,
                productId: 'clbtzf2ot335166ou12lclayh8p',
                created: new Date(),
                updated: new Date(),
            },
            {
                id: 'clbtzf2ou335174ou12jvj6xvts',
                url: 'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/products/thumbnails/a54c209c-d658-4da6-8b49-2dde1404c64d-drab-rancid-guitar',
                s3Key: null,
                productId: 'clbtzf2ot335166ou12lclayh8p',
                created: new Date(),
                updated: new Date(),
            },
            {
                id: 'clbtzf2ou335175ou12znev6rhn',
                url: 'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/products/thumbnails/c15e1b66-08e3-462e-96af-950c1147f397-flat-mysterious-zebra',
                s3Key: null,
                productId: 'clbtzf2ot335166ou12lclayh8p',
                created: new Date(),
                updated: new Date(),
            },
            {
                id: 'clbtzf2ou335176ou12e8gozf4n',
                url: 'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/products/thumbnails/1ea441b5-d765-4a85-9e69-cac1addcdc35-obnoxious-jolly-engineer',
                s3Key: null,
                productId: 'clbtzf2ot335166ou12lclayh8p',
                created: new Date(),
                updated: new Date(),
            },
        ],
        collections: [
            {
                id: 'clbtzf6qg335223ou12rrfh900u',
                productId: 'clbtzf2ot335166ou12lclayh8p',
                userId: 'clbsq8w76311124ou12qnyl6zyv',
                tokenId: 'clbtzf6pc335213ou12owyssdi5',
                origin: true,
                created: new Date(),
                updated: new Date(),
                User: {
                    id: 'clbsq8w76311124ou12qnyl6zyv',
                    email: 'maria.matveyeva.art@gmail.com',
                    sub: 'auth0|639e75a475fc227f53b000bb',
                    emailVerified: null,
                    firstName: 'Maria (Marija)',
                    lastName: 'Matveyeva (Matvejeva)',
                    nickname: 'Maria Matveyeva',
                    password: null,
                    phone: '+371 27105425',
                    image: 'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/users/avatar/c8255a98-1795-408b-88cb-06620204455f-ambitious-puny-ice',
                    s3Key: 'users/avatar/c8255a98-1795-408b-88cb-06620204455f-ambitious-puny-ice',
                    biography:
                        'I believe that the world already is full of trouble and of things that trigger negative emotions, so art should be full of light and positivity, it should inspire the person who looks at it, it should catch the viewer’s fantasy, it should emanate goodness.\r\n\r\nI believe that an artist, like a musician, can change the viewer’s mood to make it better.\r\n\r\nI love people and nature. I love painting them, love the play of light and darkness, and the lively playing of colors.\r\n\r\nMostly I paint using oil colors and watercolor. After learning the technique for painting icons, I fell in love with painting in layers.\r\n\r\nWorking in oil, I like to combine transparency with applying paint in dense brush strokes. This enables me to create depth and softness, to create a new dimension.',
                    gender: 'FEMALE',
                    birthdate: new Date(),
                    sns: [
                        {
                            url: 'https://www.instagram.com/maria.matveyeva.art/',
                            name: 'instagram',
                        },
                        {
                            url: 'https://www.facebook.com/maria.matveyeva.art',
                            name: 'facebook',
                        },
                        {
                            url: 'https://www.tricera.net/ja/artist/painters/8107665',
                            name: 'website',
                        },
                    ],
                    hazamaAddress: 'hcMrm7HLLwGKZuWscGRgZ73XVBLJUyU47r',
                    hazamaWallet: null,
                    hazamaOriginalDomain: null,
                    salt: '1a1c7aee11fef22063aeca2ff087a40a',
                    iv: '57b780d069aba908c6ebdfde50d35d4a',
                    encryptedWif:
                        '8c85067116ddf1648cb63a5e01c191e1e874d8f8807d0eb6e479886ee204e4ae5bae1e64d46be01155d6080cb563b8da6659df33c0d2f111d320d00ed9ca5676',
                    stripeCustomerId: null,
                    role: 'CREATOR',
                    avatar: 'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/users/avatar/c8255a98-1795-408b-88cb-06620204455f-ambitious-puny-ice',
                    slug: 'maria-matveyeva',
                    wpSlug: 'wp-8ab039da-059f-41f6-9534-1887f071f22c',
                    deleted: false,
                    operator: false,
                    countryId: 'ckv7v4mtw0379hx129tdt8z83',
                    created: new Date(),
                    updated: new Date(),
                },
            },
        ],
        sponsors: [],
    },
];
