import { IProduct } from '@lib/domain/interfaces/i-product';

export const ProductsChoiceDummy: IProduct[] = [
    {
        id: 'clbvwbz71431081ou12kkh6b0v8',
        name: 'Golden Token',
        description:
            'Abstract artwork was done with gold patina (liquid gold) on black canvas.\r\nBinary numbers and parallel lines create an unusual abstract composition with a 3D effect.\r\n\r\nAnastasia Vasilyeva is a contemporary artist living in Switzerland who pushes her viewers into the world of scientific art. Since 2018, her paintings have been presented at exhibitions in Europe and the USA. She is a prize-winner of art competitions organized by Artbox Gallery (Miami Art Week, Wynwood, USA. Presented by Artbox Project MIAMI2.0. Semi-finalist).\r\n\r\nNow available as NFT only on HINATA-NFT.',
        file: 'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/tokens/0a1c8c6d-0640-4c8b-a876-37364816ddb7-gifted-rotten-train.jpg',
        previewFile: null,
        minimizedImage:
            'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/tokens/a4f6a6bb-31e7-4267-8202-77aad524822a-mini-bald-brief-potato',
        s3Key: 'tokens/0a1c8c6d-0640-4c8b-a876-37364816ddb7-gifted-rotten-train.jpg',
        previewS3Key: null,
        miniS3Key: 'tokens/a4f6a6bb-31e7-4267-8202-77aad524822a-mini-bald-brief-potato',
        streamingId: null,
        slug: 'anastasia-golden-token',
        currency: 'USD',
        hotChoice: true,
        tags: ['gold', 'binary', 'token', 'science', 'crypto', 'informatics'],
        productStockId: 'clbvwbz71431082ou12inbmyxrb',
        tagId: null,
        price: 300,
        status: 'APPROVED',
        remarks: '',
        disableDownload: false,
        soldout: false,
        published: true,
        deleted: false,
        created: new Date(),

        updated: new Date(),
        rights: [
            {
                id: 'clbvwbz71431084ou1208i8dcen',
                name: 'R001',
                productId: 'clbvwbz71431081ou12kkh6b0v8',
                created: new Date(),
                updated: new Date(),
            },
        ],
        categories: [
            {
                id: '12',
                productId: 'clbvwbz71431081ou12kkh6b0v8',
                categoryId: 'ckv7v4np21713hx12brcv057e',
                created: new Date(),
                updated: new Date(),
                Category: {
                    id: 'ckv7v4np21713hx12brcv057e',
                    name: 'Art',
                    created: new Date(),
                    updated: new Date(),
                },
            },
        ],
        tag: null,
        stock: {
            id: 'clbvwbz71431082ou12inbmyxrb',
            stock: 1,
            lastNumber: 1,
            maxNumber: 1,
            created: new Date(),
            updated: new Date(),
        },
        views: {
            id: 'clbvwbz7x431112ou12cxwukxd9',
            views: 11,
            productId: 'clbvwbz71431081ou12kkh6b0v8',
            created: new Date(),
            updated: new Date(),
        },
        thumbnails: [
            {
                id: 'clbvwbz71431088ou12rqq0ai1b',
                url: 'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/products/thumbnails/4f4e0aa1-8a07-412e-a282-5a5a9d343809-purple-thankful-afternoon',
                s3Key: null,
                productId: 'clbvwbz71431081ou12kkh6b0v8',
                created: new Date(),
                updated: new Date(),
            },
            {
                id: 'clbvwbz71431089ou12m2popn7s',
                url: 'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/products/thumbnails/407b3696-b001-4249-9930-ad1a356a3d1b-happy-burly-yottabyte',
                s3Key: null,
                productId: 'clbvwbz71431081ou12kkh6b0v8',
                created: new Date(),
                updated: new Date(),
            },
            {
                id: 'clbvwbz71431090ou12nhyh7t0g',
                url: 'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/products/thumbnails/de0e2dca-1a1f-470e-9fed-8133662ccb5c-dead-short-hospital',
                s3Key: null,
                productId: 'clbvwbz71431081ou12kkh6b0v8',
                created: new Date(),
                updated: new Date(),
            },
        ],
        collections: [
            {
                id: 'clbvwc4v5431134ou12rywucjyh',
                productId: 'clbvwbz71431081ou12kkh6b0v8',
                userId: 'clbkpvemh921719qi2kk9sg6qog',
                tokenId: 'clbvwc4ui431124ou12gyw4l0am',
                origin: true,
                created: new Date(),
                updated: new Date(),
                User: {
                    id: 'clbkpvemh921719qi2kk9sg6qog',
                    email: 'anavasilyeva@gmail.com',
                    sub: 'auth0|6397119dffa0ee78c0940d3f',
                    emailVerified: null,
                    firstName: 'Vasilyeva',
                    lastName: 'Anastasia',
                    nickname: 'Anastasia Vasilyeva',
                    password: null,
                    phone: '0791292124',
                    image: 'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/users/avatar/ccb5186c-563c-436a-ba06-7a5dd93cbf7c-shallow-boring-ocean',
                    s3Key: 'users/avatar/ccb5186c-563c-436a-ba06-7a5dd93cbf7c-shallow-boring-ocean',
                    biography:
                        'Anastasia Vasilyeva was born in 1982 in St.Petersburg (Russia) where she grew up. In 2008 she moved to Switzerland where she\'s been living since then. \r\n\r\nAnastasia Vasilyeva is an artist dedicated to abstract conceptual art. In her works, she combines art with motifs and themes of mathematics as well as computer science. Her work also focuses on current social problems. Inspired by Mark Rothko, Jackson Pollack, Kandinsky, and Gerhard Richter, Anastasia Vasilyeva makes a conceptual contribution to Contemporary Art. \r\n\r\nBorn in an artist-family (4th generation) she learned the basic painting techniques from her father and continued to further develop them in various painting courses. Anastasia is also very interested in the history of art. The art exhibitions of classical and modern works of art always give her new inputs and inspirations for her work.\r\n\r\nSince 2016 Anastasia Vasilyeva has been exhibiting her works in certain art galleries, museums as well as in large IT and insurance companies in the USA, Switzerland, Germany, and Estonia.\r\n2021 - Exhibition in Darwin Museum in Moscow, The project EARTH2021;\r\n2019 -Selected as Semi-finalist in the project MIAMI2.0 organized by ARTBOX.Projects. "School board N8" was presented in Wynwood during Art Basel Miami Week.\r\n2018 -The diptych "Glacier" was owned by the MUSEUM OF ART in Narva, Estonia;  \r\n\r\n\r\nInfluences\r\nMark Rothko, Jackson Pollack, Kandinsky, Gerhard Richter, Kazimir Malevich\r\n\r\n\r\nEducation\r\n2021-2021 MoMa Courses, specialization Modern and Contemporary Art and Design New York, New York, United States \r\n2016-2017 Mix media contemporary artist Sempach, Switzerland \r\n1999-2004 Dip. Applied Mathematician St.Petersburg, Russia ',
                    gender: 'FEMALE',
                    birthdate: new Date(),
                    sns: [
                        {
                            url: 'https://www.youtube.com/@AnastasiaVasilyeva',
                            name: 'youtube',
                        },
                        {
                            url: 'https://www.anavasilyeva.com/collections?isHome=1',
                            name: 'website',
                        },
                        {
                            url: 'https://www.instagram.com/anastasiavasiljeva/',
                            name: 'instagram',
                        },
                        {
                            url: 'https://twitter.com/VasilyevaArt',
                            name: 'twitter',
                        },
                    ],
                    hazamaAddress: 'hKwpAGMe5ybTJVWTRLRTCgyt7HFaV8odii',
                    hazamaWallet: null,
                    hazamaOriginalDomain: null,
                    salt: '8e9b30935d6f504a4c169385c0c445aa',
                    iv: 'b8b95e5859cca4263a3c06f9399861da',
                    encryptedWif:
                        '690edaf11c11b1d544373c759ac5ae82a6d5d3bd525607a5c3c6a6c25c5e34979d6b340395af0cd0b814b8d525d7046ba2c53896ca07b10eb69f42d47f587fbb',
                    stripeCustomerId: null,
                    role: 'CREATOR',
                    avatar: 'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/users/avatar/ccb5186c-563c-436a-ba06-7a5dd93cbf7c-shallow-boring-ocean',
                    slug: 'anastasia-vasilyeva',
                    wpSlug: 'wp-88af923f-83fd-4aa1-8042-0d6bd08a5daf',
                    deleted: false,
                    operator: false,
                    countryId: 'ckv7v4n761052hx128tpnfswx',
                    created: new Date(),
                    updated: new Date(),
                },
            },
        ],
        sponsors: [],
    },
    {
        id: 'clbvtcdmv420270g72k0gyne8bs',
        name: 'Winter sketch Path to the river',
        description:
            'This painting is inspired by one winter day.\r\nSnowy footpath to the river. A beautiful landscape that pleases the eye.\r\nAll colors of the winter palette.\r\nFrom warm oranges to cool blues and turquoises.\r\nPasty painting.',
        file: 'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/tokens/bd62fea4-ca58-4e95-9f18-a7285440b8bf-spicy-fancy-sunset.JPG',
        previewFile: null,
        minimizedImage:
            'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/tokens/5e3b6e28-85d7-4c43-b39f-c043d39398d4-mini-putrid-teeny-plumber',
        s3Key: 'tokens/bd62fea4-ca58-4e95-9f18-a7285440b8bf-spicy-fancy-sunset.JPG',
        previewS3Key: null,
        miniS3Key: 'tokens/5e3b6e28-85d7-4c43-b39f-c043d39398d4-mini-putrid-teeny-plumber',
        streamingId: null,
        slug: 'winter-sketch-path-to-the-river',
        currency: 'USD',
        hotChoice: true,
        tags: [],
        productStockId: 'clbvtcdmv420271g72kksctlrsn',
        tagId: null,
        price: 270,
        status: 'APPROVED',
        remarks: '',
        disableDownload: false,
        soldout: false,
        published: true,
        deleted: false,
        created: new Date(),
        updated: new Date(),
        rights: [
            {
                id: 'clbvtcdmv420273g72k8rirh8by',
                name: 'R001',
                productId: 'clbvtcdmv420270g72k0gyne8bs',
                created: new Date(),
                updated: new Date(),
            },
        ],
        categories: [
            {
                id: 'clbvtcdmv420273g72k8rirh8by',
                productId: 'clbvtcdmv420270g72k0gyne8bs',
                categoryId: 'ckv7v4np21713hx12brcv057e',
                created: new Date(),
                updated: new Date(),
                Category: {
                    id: 'ckv7v4np21713hx12brcv057e',
                    name: 'Art',
                    created: new Date(),
                    updated: new Date(),
                },
            },
        ],
        tag: null,
        stock: {
            id: 'clbvtcdmv420271g72kksctlrsn',
            stock: 1,
            lastNumber: 1,
            maxNumber: 1,
            created: new Date(),
            updated: new Date(),
        },
        views: {
            id: 'clbvtcdo3420289g72ke4z8fsb6',
            views: 9,
            productId: 'clbvtcdmv420270g72k0gyne8bs',
            created: new Date(),
            updated: new Date(),
        },
        thumbnails: [],
        collections: [
            {
                id: 'clbvtcjbd420311g72k686yfvda',
                productId: 'clbvtcdmv420270g72k0gyne8bs',
                userId: 'claol3ims406132612ks0t1fkc7',
                tokenId: 'clbvtcjac420301g72knhud1x36',
                origin: true,
                created: new Date(),
                updated: new Date(),
                User: {
                    birthdate: new Date(),
                    id: 'claol3ims406132612ks0t1fkc7',
                    email: 'lukina.artist@gmail.com',
                    sub: 'auth0|63796c049740d5ecb0c8cfd3',
                    emailVerified: null,
                    firstName: 'Elena',
                    lastName: 'Lukina',
                    nickname: 'J.Lu',
                    password: null,
                    phone: '+37129513247',
                    image: 'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/users/avatar/b1245a15-8605-4b7b-9dfc-ed40d2ea52eb-burly-orange-baby',
                    s3Key: 'users/avatar/b1245a15-8605-4b7b-9dfc-ed40d2ea52eb-burly-orange-baby',
                    biography:
                        'Art for me is not only a way of expression, but also a source of joy and love! \r\n\r\nJ.Lu is a prizewinning artist from Latvia whose paintings have been exhibited in solo and group shows internationally. Inspired by the beauty of nature, Lukina creates impressionist style landscapes, botanical works, animal portraits, and more in oil on canvas. Her work is characterized by great technical skill and conjure up a warmth and nostalgia through soft color palettes and smooth textures.',
                    gender: 'FEMALE',
                    sns: [
                        {
                            url: 'https://www.singulart.com/en/artist/elena-lukina-8963',
                            name: 'website',
                        },
                        {
                            url: 'https://www.facebook.com/ArtElenaLukina/',
                            name: 'facebook',
                        },
                    ],
                    hazamaAddress: 'hMuABw4Y1buXQPaBURZYAsraQJrKZuPUib',
                    hazamaWallet: null,
                    hazamaOriginalDomain: null,
                    salt: '42bd99b0dd94348e4ae81b1b6156071e',
                    iv: '0c8c220ae4a9af48cf06193c7c0d8968',
                    encryptedWif:
                        '1d95c8094e914b8c058aff5c46323587c6a9ab1aa2ba767383422ff654b6ea67fe588746dfc59b1179efce4f1078bc7c07569bc4f49f512aa805c165f56b2137',
                    stripeCustomerId: null,
                    role: 'CREATOR',
                    avatar: 'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/users/avatar/b1245a15-8605-4b7b-9dfc-ed40d2ea52eb-burly-orange-baby',
                    slug: 'j-lu',
                    wpSlug: 'wp-51231ba1-5ff8-43a8-83c9-ca11a2f2a8fa',
                    deleted: false,
                    operator: false,
                    countryId: 'ckv7v4mtw0379hx129tdt8z83',
                    created: new Date(),
                    updated: new Date(),
                },
            },
        ],
        sponsors: [],
    },
    {
        id: 'clbu0gw0m331997g72kasvmb19y',
        name: 'Outumn vibes',
        description: null,
        file: 'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/tokens/f8a2be8d-8679-4a1f-8a17-abdb300fe041-mango-clean-river.jpg',
        previewFile: null,
        minimizedImage:
            'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/tokens/91f9f31b-235b-4b62-b6cc-ba143e757322-mini-teeny-cold-flower',
        s3Key: 'tokens/f8a2be8d-8679-4a1f-8a17-abdb300fe041-mango-clean-river.jpg',
        previewS3Key: null,
        miniS3Key: 'tokens/91f9f31b-235b-4b62-b6cc-ba143e757322-mini-teeny-cold-flower',
        streamingId: null,
        slug: 'outumn-vibes-333',
        currency: 'USD',
        hotChoice: true,
        tags: [],
        productStockId: 'clbu0gw0n331998g72klytk81o5',
        tagId: null,
        price: 200,
        status: 'APPROVED',
        remarks: '',
        disableDownload: false,
        soldout: false,
        published: true,
        deleted: false,
        created: new Date(),
        updated: new Date(),
        rights: [
            {
                id: 'clbu0gw0n332000g72koeqeu5ie',
                name: 'R001',
                productId: 'clbu0gw0m331997g72kasvmb19y',
                created: new Date(),
                updated: new Date(),
            },
        ],
        categories: [
            {
                id: 'clbvtcdmv420273g72k8rirh8by',
                productId: 'clbu0gw0m331997g72kasvmb19y',
                categoryId: 'ckv7v4np21713hx12brcv057e',
                created: new Date(),
                updated: new Date(),
                Category: {
                    id: 'ckv7v4np21713hx12brcv057e',
                    name: 'Art',
                    created: new Date(),
                    updated: new Date(),
                },
            },
        ],
        tag: null,
        stock: {
            id: 'clbu0gw0n331998g72klytk81o5',
            stock: 1,
            lastNumber: 1,
            maxNumber: 1,
            created: new Date(),
            updated: new Date(),
        },
        views: {
            id: 'clbu0gw34332024g72kwshzbeur',
            views: 10,
            productId: 'clbu0gw0m331997g72kasvmb19y',
            created: new Date(),
            updated: new Date(),
        },
        thumbnails: [
            {
                id: 'clbu0gw0n332004g72kdbfe3kk0',
                url: 'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/products/thumbnails/efad364c-8ac9-44dc-9cf5-c7f1ff47b840-putrid-loud-fountain',
                s3Key: null,
                productId: 'clbu0gw0m331997g72kasvmb19y',
                created: new Date(),
                updated: new Date(),
            },
            {
                id: 'clbu0gw0n332005g72krz1zsxvn',
                url: 'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/products/thumbnails/521313f2-22cf-496a-bdc5-1b126690cb70-hot-mysterious-lunch',
                s3Key: null,
                productId: 'clbu0gw0m331997g72kasvmb19y',
                created: new Date(),
                updated: new Date(),
            },
        ],
        collections: [
            {
                id: 'clbu0h060332046g72k8g0s5nal',
                productId: 'clbu0gw0m331997g72kasvmb19y',
                userId: 'clbsq8w76311124ou12qnyl6zyv',
                tokenId: 'clbu0h050332036g72klgzai1ez',
                origin: true,
                created: new Date(),
                updated: new Date(),
                User: {
                    birthdate: new Date(),
                    id: 'clbsq8w76311124ou12qnyl6zyv',
                    email: 'maria.matveyeva.art@gmail.com',
                    sub: 'auth0|639e75a475fc227f53b000bb',
                    emailVerified: null,
                    firstName: 'Maria (Marija)',
                    lastName: 'Matveyeva (Matvejeva)',
                    nickname: 'Maria Matveyeva',
                    password: null,
                    phone: '+371 27105425',
                    image: 'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/users/avatar/c8255a98-1795-408b-88cb-06620204455f-ambitious-puny-ice',
                    s3Key: 'users/avatar/c8255a98-1795-408b-88cb-06620204455f-ambitious-puny-ice',
                    biography:
                        'I believe that the world already is full of trouble and of things that trigger negative emotions, so art should be full of light and positivity, it should inspire the person who looks at it, it should catch the viewer’s fantasy, it should emanate goodness.\r\n\r\nI believe that an artist, like a musician, can change the viewer’s mood to make it better.\r\n\r\nI love people and nature. I love painting them, love the play of light and darkness, and the lively playing of colors.\r\n\r\nMostly I paint using oil colors and watercolor. After learning the technique for painting icons, I fell in love with painting in layers.\r\n\r\nWorking in oil, I like to combine transparency with applying paint in dense brush strokes. This enables me to create depth and softness, to create a new dimension.',
                    gender: 'FEMALE',
                    sns: [
                        {
                            url: 'https://www.instagram.com/maria.matveyeva.art/',
                            name: 'instagram',
                        },
                        {
                            url: 'https://www.facebook.com/maria.matveyeva.art',
                            name: 'facebook',
                        },
                        {
                            url: 'https://www.tricera.net/ja/artist/painters/8107665',
                            name: 'website',
                        },
                    ],
                    hazamaAddress: 'hcMrm7HLLwGKZuWscGRgZ73XVBLJUyU47r',
                    hazamaWallet: null,
                    hazamaOriginalDomain: null,
                    salt: '1a1c7aee11fef22063aeca2ff087a40a',
                    iv: '57b780d069aba908c6ebdfde50d35d4a',
                    encryptedWif:
                        '8c85067116ddf1648cb63a5e01c191e1e874d8f8807d0eb6e479886ee204e4ae5bae1e64d46be01155d6080cb563b8da6659df33c0d2f111d320d00ed9ca5676',
                    stripeCustomerId: null,
                    role: 'CREATOR',
                    avatar: 'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/users/avatar/c8255a98-1795-408b-88cb-06620204455f-ambitious-puny-ice',
                    slug: 'maria-matveyeva',
                    wpSlug: 'wp-8ab039da-059f-41f6-9534-1887f071f22c',
                    deleted: false,
                    operator: false,
                    countryId: 'ckv7v4mtw0379hx129tdt8z83',
                    created: new Date(),
                    updated: new Date(),
                },
            },
        ],
        sponsors: [],
    },
    {
        id: 'clbribgu1290928g72kzkzbkyek',
        name: 'Bullfinch on a rowan branch',
        description: null,
        file: 'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/tokens/bae0bde0-9bf7-43cd-be0c-97df30ccc792-limited-tight-ability.jpg',
        previewFile: null,
        minimizedImage:
            'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/tokens/988b560f-7993-4b04-a5f6-d3c98bcf0c5e-mini-microscopic-ugly-parrot',
        s3Key: 'tokens/bae0bde0-9bf7-43cd-be0c-97df30ccc792-limited-tight-ability.jpg',
        previewS3Key: null,
        miniS3Key: 'tokens/988b560f-7993-4b04-a5f6-d3c98bcf0c5e-mini-microscopic-ugly-parrot',
        streamingId: null,
        slug: 'bullfinch-on-a-rowan-branch',
        currency: 'USD',
        hotChoice: true,
        tags: [],
        productStockId: 'clbribgu2290929g72k3vj2ixvc',
        tagId: null,
        price: 300,
        status: 'APPROVED',
        remarks: '',
        disableDownload: false,
        soldout: false,
        published: true,
        deleted: false,
        created: new Date(),
        updated: new Date(),
        rights: [
            {
                id: 'clbribgu2290931g72kordsd103',
                name: 'R001',
                productId: 'clbribgu1290928g72kzkzbkyek',
                created: new Date(),
                updated: new Date(),
            },
        ],
        categories: [
            {
                id: 'clbvtcdmv420273g72k8rirh8by',
                productId: 'clbrf2abg282511g72k2icpjje5',
                categoryId: 'ckv7v4np21713hx12brcv057e',
                created: new Date(),
                updated: new Date(),
                Category: {
                    id: 'ckv7v4np21713hx12brcv057e',
                    name: 'Art',
                    created: new Date(),
                    updated: new Date(),
                },
            },
        ],
        tag: null,
        stock: {
            id: 'clbribgu2290929g72k3vj2ixvc',
            stock: 1,
            lastNumber: 1,
            maxNumber: 1,
            created: new Date(),
            updated: new Date(),
        },
        views: {
            id: 'clbribgvj290947g72kxn3b6sc6',
            views: 11,
            productId: 'clbribgu1290928g72kzkzbkyek',
            created: new Date(),
            updated: new Date(),
        },
        thumbnails: [],
        collections: [
            {
                id: 'clbribk2o290969g72k4nvhz9qi',
                productId: 'clbribgu1290928g72kzkzbkyek',
                userId: 'claol3ims406132612ks0t1fkc7',
                tokenId: 'clbribk1p290959g72kj9hgcbcr',
                origin: true,
                created: new Date(),
                updated: new Date(),
                User: {
                    birthdate: new Date(),
                    id: 'claol3ims406132612ks0t1fkc7',
                    email: 'lukina.artist@gmail.com',
                    sub: 'auth0|63796c049740d5ecb0c8cfd3',
                    emailVerified: null,
                    firstName: 'Elena',
                    lastName: 'Lukina',
                    nickname: 'J.Lu',
                    password: null,
                    phone: '+37129513247',
                    image: 'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/users/avatar/b1245a15-8605-4b7b-9dfc-ed40d2ea52eb-burly-orange-baby',
                    s3Key: 'users/avatar/b1245a15-8605-4b7b-9dfc-ed40d2ea52eb-burly-orange-baby',
                    biography:
                        'Art for me is not only a way of expression, but also a source of joy and love! \r\n\r\nJ.Lu is a prizewinning artist from Latvia whose paintings have been exhibited in solo and group shows internationally. Inspired by the beauty of nature, Lukina creates impressionist style landscapes, botanical works, animal portraits, and more in oil on canvas. Her work is characterized by great technical skill and conjure up a warmth and nostalgia through soft color palettes and smooth textures.',
                    gender: 'FEMALE',
                    sns: [
                        {
                            url: 'https://www.singulart.com/en/artist/elena-lukina-8963',
                            name: 'website',
                        },
                        {
                            url: 'https://www.facebook.com/ArtElenaLukina/',
                            name: 'facebook',
                        },
                    ],
                    hazamaAddress: 'hMuABw4Y1buXQPaBURZYAsraQJrKZuPUib',
                    hazamaWallet: null,
                    hazamaOriginalDomain: null,
                    salt: '42bd99b0dd94348e4ae81b1b6156071e',
                    iv: '0c8c220ae4a9af48cf06193c7c0d8968',
                    encryptedWif:
                        '1d95c8094e914b8c058aff5c46323587c6a9ab1aa2ba767383422ff654b6ea67fe588746dfc59b1179efce4f1078bc7c07569bc4f49f512aa805c165f56b2137',
                    stripeCustomerId: null,
                    role: 'CREATOR',
                    avatar: 'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/users/avatar/b1245a15-8605-4b7b-9dfc-ed40d2ea52eb-burly-orange-baby',
                    slug: 'j-lu',
                    wpSlug: 'wp-51231ba1-5ff8-43a8-83c9-ca11a2f2a8fa',
                    deleted: false,
                    operator: false,
                    countryId: 'ckv7v4mtw0379hx129tdt8z83',
                    created: new Date(),
                    updated: new Date(),
                },
            },
        ],
        sponsors: [],
    },
    {
        id: 'clbrf2abg282511g72k2icpjje5',
        name: 'Roses 5.',
        description:
            'Roses 5. Delicate rose bush: pink and white flowers on an abstract light abstract background, created with brushes and spatula, drops and splashes. The picture is filled with positive, solar energy, tenderness. Part of an ongoing series of flower arrangements. Expressionism. Impressionism. Used high quality materials. Acrylic painting on canvas. The sides are painted white.',
        file: 'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/tokens/ccbd1b46-5a3d-4d14-97e5-90f5269a7958-aggressive-sticky-keyboard.JPG',
        previewFile: null,
        minimizedImage:
            'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/tokens/98e1f9e3-9d40-4646-b85a-8151bbbd9ab9-mini-petite-yellow-quill',
        s3Key: 'tokens/ccbd1b46-5a3d-4d14-97e5-90f5269a7958-aggressive-sticky-keyboard.JPG',
        previewS3Key: null,
        miniS3Key: 'tokens/98e1f9e3-9d40-4646-b85a-8151bbbd9ab9-mini-petite-yellow-quill',
        streamingId: null,
        slug: 'iryna-roses5',
        currency: 'USD',
        hotChoice: true,
        tags: [],
        productStockId: 'clbrf2abg282512g72k05tvrytg',
        tagId: null,
        price: 935,
        status: 'APPROVED',
        remarks: '',
        disableDownload: false,
        soldout: false,
        published: true,
        deleted: false,
        created: new Date(),
        updated: new Date(),
        rights: [
            {
                id: 'clbrf2abg282514g72ktvzbc0o7',
                name: 'R001',
                productId: 'clbrf2abg282511g72k2icpjje5',
                created: new Date(),
                updated: new Date(),
            },
        ],
        categories: [
            {
                id: 'clbvtcdmv420273g72k8rirh8by',
                productId: 'clbrf2abg282511g72k2icpjje5',
                categoryId: 'ckv7v4np21713hx12brcv057e',
                created: new Date(),
                updated: new Date(),
                Category: {
                    id: 'ckv7v4np21713hx12brcv057e',
                    name: 'Art',
                    created: new Date(),
                    updated: new Date(),
                },
            },
        ],
        tag: null,
        stock: {
            id: 'clbrf2abg282512g72k05tvrytg',
            stock: 1,
            lastNumber: 1,
            maxNumber: 1,
            created: new Date(),
            updated: new Date(),
        },
        views: {
            id: 'clbrf2acp282530g72kbyjb3vv7',
            views: 17,
            productId: 'clbrf2abg282511g72k2icpjje5',
            created: new Date(),
            updated: new Date(),
        },
        thumbnails: [],
        collections: [
            {
                id: 'clbrf2e1f282552g72kyl2vo509',
                productId: 'clbrf2abg282511g72k2icpjje5',
                userId: 'cl9obg2yl269789712krsxvrb9a',
                tokenId: 'clbrf2e0f282542g72ky9164ii2',
                origin: true,
                created: new Date(),
                updated: new Date(),
                User: {
                    id: 'cl9obg2yl269789712krsxvrb9a',
                    email: 'irynakastsova@gmail.com',
                    sub: 'auth0|6357f5a4cad6defe4fb04aac',
                    emailVerified: null,
                    firstName: 'IRYNA',
                    lastName: 'KASTSOVA',
                    nickname: 'Irina Mask',
                    password: null,
                    phone: '+375293055697',
                    image: 'https://amatsuhi-prod-images.s3.amazonaws.com/users/avatar/3e749f0e-1d75-4639-9dc5-4d31493243f2-sparse-greasy-lunch',
                    s3Key: 'users/avatar/3e749f0e-1d75-4639-9dc5-4d31493243f2-sparse-greasy-lunch',
                    biography:
                        'Hello and welcome to my profile! \r\n\r\nBorn in 1976 in Poland. Warsaw. Graduated from the Art Belarusian Academy of Arts. Department: monumental and decorative painting. Then I worked in creative workshops. \r\n\r\nI paint in the style of realism, impressionism, pop art, expressionism. I love experiments in painting. An important place in my work is occupied by nature in all its manifestations. I strive to comprehend and reveal for myself and for the viewer the inner life of nature in all its diversity. At the same time, I really like to paint abstract paintings, when working on which the emotional aspect is crucial, and color is considered as an object. The visualization process is based on deliberate coincidence and precise development. In the center of the work are colors, light, structures and shapes that I use in a certain harmony with various techniques. I paint portraits to order from a photograph in the style of realism and pop art. I have been working with online galleries since 2020. \r\n\r\nI live and work in Poland. My paintings are full of life and joy, so... if you want, you can have a piece of this joy and happiness at home.',
                    gender: 'FEMALE',
                    birthdate: new Date(),
                    sns: [
                        {
                            url: 'https://www.facebook.com/media/set/?vanity=irynakastsova&set=a.2944054682407676',
                            name: 'facebook',
                        },
                        {
                            url: 'https://www.singulart.com/en/artist/iryna-kastsova-8217',
                            name: 'website',
                        },
                        {
                            url: 'https://twitter.com/ikastsova',
                            name: 'twitter',
                        },
                        {
                            url: 'https://www.instagram.com/irynakastsovaart/',
                            name: 'instagram',
                        },
                    ],
                    hazamaAddress: 'hFaZjr9Hs1t4UAx6pv9jEZDBq8ytHsEpXs',
                    hazamaWallet: null,
                    hazamaOriginalDomain: null,
                    salt: '2c8417e7d672801a213a9332c40a69ed',
                    iv: 'e55c89bd55e0f041c1fb78e1ebbe3cc6',
                    encryptedWif:
                        '6a8799361d9e5f3d4d3f59587f991b96ade06492cdbf402cdb81408b67408cc1f731bfbba8f58c676fdff8a1276f82f1f63ca1aa14aa6d2fdae6724efd1f9529',
                    stripeCustomerId: null,
                    role: 'CREATOR',
                    avatar: 'https://amatsuhi-prod-images.s3.amazonaws.com/users/avatar/3e749f0e-1d75-4639-9dc5-4d31493243f2-sparse-greasy-lunch',
                    slug: 'iryna',
                    wpSlug: 'wp-5e768aae-2c6d-48cf-8800-24f2bffc1851',
                    deleted: false,
                    operator: false,
                    countryId: 'ckv7v4n2i0806hx12rlrlg5bl',
                    created: new Date(),
                    updated: new Date(),
                },
            },
        ],
        sponsors: [],
    },
    {
        id: 'clbvtcdmv420270g72k0gyne8bs',
        name: 'Winter sketch Path to the river',
        description:
            'This painting is inspired by one winter day.\r\nSnowy footpath to the river. A beautiful landscape that pleases the eye.\r\nAll colors of the winter palette.\r\nFrom warm oranges to cool blues and turquoises.\r\nPasty painting.',
        file: 'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/tokens/bd62fea4-ca58-4e95-9f18-a7285440b8bf-spicy-fancy-sunset.JPG',
        previewFile: null,
        minimizedImage:
            'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/tokens/5e3b6e28-85d7-4c43-b39f-c043d39398d4-mini-putrid-teeny-plumber',
        s3Key: 'tokens/bd62fea4-ca58-4e95-9f18-a7285440b8bf-spicy-fancy-sunset.JPG',
        previewS3Key: null,
        miniS3Key: 'tokens/5e3b6e28-85d7-4c43-b39f-c043d39398d4-mini-putrid-teeny-plumber',
        streamingId: null,
        slug: 'winter-sketch-path-to-the-river',
        currency: 'USD',
        hotChoice: true,
        tags: [],
        productStockId: 'clbvtcdmv420271g72kksctlrsn',
        tagId: null,
        price: 270,
        status: 'APPROVED',
        remarks: '',
        disableDownload: false,
        soldout: false,
        published: true,
        deleted: false,
        created: new Date(),
        updated: new Date(),
        rights: [
            {
                id: 'clbvtcdmv420273g72k8rirh8by',
                name: 'R001',
                productId: 'clbvtcdmv420270g72k0gyne8bs',
                created: new Date(),
                updated: new Date(),
            },
        ],
        categories: [
            {
                id: 'clbvtcdmv420273g72k8rirh8by',
                productId: 'clbvtcdmv420270g72k0gyne8bs',
                categoryId: 'ckv7v4np21713hx12brcv057e',
                created: new Date(),
                updated: new Date(),
                Category: {
                    id: 'ckv7v4np21713hx12brcv057e',
                    name: 'Art',
                    created: new Date(),
                    updated: new Date(),
                },
            },
        ],
        tag: null,
        stock: {
            id: 'clbvtcdmv420271g72kksctlrsn',
            stock: 1,
            lastNumber: 1,
            maxNumber: 1,
            created: new Date(),
            updated: new Date(),
        },
        views: {
            id: 'clbvtcdo3420289g72ke4z8fsb6',
            views: 9,
            productId: 'clbvtcdmv420270g72k0gyne8bs',
            created: new Date(),
            updated: new Date(),
        },
        thumbnails: [],
        collections: [
            {
                id: 'clbvtcjbd420311g72k686yfvda',
                productId: 'clbvtcdmv420270g72k0gyne8bs',
                userId: 'claol3ims406132612ks0t1fkc7',
                tokenId: 'clbvtcjac420301g72knhud1x36',
                origin: true,
                created: new Date(),
                updated: new Date(),
                User: {
                    birthdate: new Date(),
                    id: 'claol3ims406132612ks0t1fkc7',
                    email: 'lukina.artist@gmail.com',
                    sub: 'auth0|63796c049740d5ecb0c8cfd3',
                    emailVerified: null,
                    firstName: 'Elena',
                    lastName: 'Lukina',
                    nickname: 'J.Lu',
                    password: null,
                    phone: '+37129513247',
                    image: 'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/users/avatar/b1245a15-8605-4b7b-9dfc-ed40d2ea52eb-burly-orange-baby',
                    s3Key: 'users/avatar/b1245a15-8605-4b7b-9dfc-ed40d2ea52eb-burly-orange-baby',
                    biography:
                        'Art for me is not only a way of expression, but also a source of joy and love! \r\n\r\nJ.Lu is a prizewinning artist from Latvia whose paintings have been exhibited in solo and group shows internationally. Inspired by the beauty of nature, Lukina creates impressionist style landscapes, botanical works, animal portraits, and more in oil on canvas. Her work is characterized by great technical skill and conjure up a warmth and nostalgia through soft color palettes and smooth textures.',
                    gender: 'FEMALE',
                    sns: [
                        {
                            url: 'https://www.singulart.com/en/artist/elena-lukina-8963',
                            name: 'website',
                        },
                        {
                            url: 'https://www.facebook.com/ArtElenaLukina/',
                            name: 'facebook',
                        },
                    ],
                    hazamaAddress: 'hMuABw4Y1buXQPaBURZYAsraQJrKZuPUib',
                    hazamaWallet: null,
                    hazamaOriginalDomain: null,
                    salt: '42bd99b0dd94348e4ae81b1b6156071e',
                    iv: '0c8c220ae4a9af48cf06193c7c0d8968',
                    encryptedWif:
                        '1d95c8094e914b8c058aff5c46323587c6a9ab1aa2ba767383422ff654b6ea67fe588746dfc59b1179efce4f1078bc7c07569bc4f49f512aa805c165f56b2137',
                    stripeCustomerId: null,
                    role: 'CREATOR',
                    avatar: 'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/users/avatar/b1245a15-8605-4b7b-9dfc-ed40d2ea52eb-burly-orange-baby',
                    slug: 'j-lu',
                    wpSlug: 'wp-51231ba1-5ff8-43a8-83c9-ca11a2f2a8fa',
                    deleted: false,
                    operator: false,
                    countryId: 'ckv7v4mtw0379hx129tdt8z83',
                    created: new Date(),
                    updated: new Date(),
                },
            },
        ],
        sponsors: [],
    },
    {
        id: 'clbu0gw0m331997g72kasvmb19y',
        name: 'Outumn vibes',
        description: null,
        file: 'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/tokens/f8a2be8d-8679-4a1f-8a17-abdb300fe041-mango-clean-river.jpg',
        previewFile: null,
        minimizedImage:
            'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/tokens/91f9f31b-235b-4b62-b6cc-ba143e757322-mini-teeny-cold-flower',
        s3Key: 'tokens/f8a2be8d-8679-4a1f-8a17-abdb300fe041-mango-clean-river.jpg',
        previewS3Key: null,
        miniS3Key: 'tokens/91f9f31b-235b-4b62-b6cc-ba143e757322-mini-teeny-cold-flower',
        streamingId: null,
        slug: 'outumn-vibes-333',
        currency: 'USD',
        hotChoice: true,
        tags: [],
        productStockId: 'clbu0gw0n331998g72klytk81o5',
        tagId: null,
        price: 200,
        status: 'APPROVED',
        remarks: '',
        disableDownload: false,
        soldout: false,
        published: true,
        deleted: false,
        created: new Date(),
        updated: new Date(),
        rights: [
            {
                id: 'clbu0gw0n332000g72koeqeu5ie',
                name: 'R001',
                productId: 'clbu0gw0m331997g72kasvmb19y',
                created: new Date(),
                updated: new Date(),
            },
        ],
        categories: [
            {
                id: 'clbvtcdmv420273g72k8rirh8by',
                productId: 'clbu0gw0m331997g72kasvmb19y',
                categoryId: 'ckv7v4np21713hx12brcv057e',
                created: new Date(),
                updated: new Date(),
                Category: {
                    id: 'ckv7v4np21713hx12brcv057e',
                    name: 'Art',
                    created: new Date(),
                    updated: new Date(),
                },
            },
        ],
        tag: null,
        stock: {
            id: 'clbu0gw0n331998g72klytk81o5',
            stock: 1,
            lastNumber: 1,
            maxNumber: 1,
            created: new Date(),
            updated: new Date(),
        },
        views: {
            id: 'clbu0gw34332024g72kwshzbeur',
            views: 10,
            productId: 'clbu0gw0m331997g72kasvmb19y',
            created: new Date(),
            updated: new Date(),
        },
        thumbnails: [
            {
                id: 'clbu0gw0n332004g72kdbfe3kk0',
                url: 'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/products/thumbnails/efad364c-8ac9-44dc-9cf5-c7f1ff47b840-putrid-loud-fountain',
                s3Key: null,
                productId: 'clbu0gw0m331997g72kasvmb19y',
                created: new Date(),
                updated: new Date(),
            },
            {
                id: 'clbu0gw0n332005g72krz1zsxvn',
                url: 'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/products/thumbnails/521313f2-22cf-496a-bdc5-1b126690cb70-hot-mysterious-lunch',
                s3Key: null,
                productId: 'clbu0gw0m331997g72kasvmb19y',
                created: new Date(),
                updated: new Date(),
            },
        ],
        collections: [
            {
                id: 'clbu0h060332046g72k8g0s5nal',
                productId: 'clbu0gw0m331997g72kasvmb19y',
                userId: 'clbsq8w76311124ou12qnyl6zyv',
                tokenId: 'clbu0h050332036g72klgzai1ez',
                origin: true,
                created: new Date(),
                updated: new Date(),
                User: {
                    birthdate: new Date(),
                    id: 'clbsq8w76311124ou12qnyl6zyv',
                    email: 'maria.matveyeva.art@gmail.com',
                    sub: 'auth0|639e75a475fc227f53b000bb',
                    emailVerified: null,
                    firstName: 'Maria (Marija)',
                    lastName: 'Matveyeva (Matvejeva)',
                    nickname: 'Maria Matveyeva',
                    password: null,
                    phone: '+371 27105425',
                    image: 'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/users/avatar/c8255a98-1795-408b-88cb-06620204455f-ambitious-puny-ice',
                    s3Key: 'users/avatar/c8255a98-1795-408b-88cb-06620204455f-ambitious-puny-ice',
                    biography:
                        'I believe that the world already is full of trouble and of things that trigger negative emotions, so art should be full of light and positivity, it should inspire the person who looks at it, it should catch the viewer’s fantasy, it should emanate goodness.\r\n\r\nI believe that an artist, like a musician, can change the viewer’s mood to make it better.\r\n\r\nI love people and nature. I love painting them, love the play of light and darkness, and the lively playing of colors.\r\n\r\nMostly I paint using oil colors and watercolor. After learning the technique for painting icons, I fell in love with painting in layers.\r\n\r\nWorking in oil, I like to combine transparency with applying paint in dense brush strokes. This enables me to create depth and softness, to create a new dimension.',
                    gender: 'FEMALE',
                    sns: [
                        {
                            url: 'https://www.instagram.com/maria.matveyeva.art/',
                            name: 'instagram',
                        },
                        {
                            url: 'https://www.facebook.com/maria.matveyeva.art',
                            name: 'facebook',
                        },
                        {
                            url: 'https://www.tricera.net/ja/artist/painters/8107665',
                            name: 'website',
                        },
                    ],
                    hazamaAddress: 'hcMrm7HLLwGKZuWscGRgZ73XVBLJUyU47r',
                    hazamaWallet: null,
                    hazamaOriginalDomain: null,
                    salt: '1a1c7aee11fef22063aeca2ff087a40a',
                    iv: '57b780d069aba908c6ebdfde50d35d4a',
                    encryptedWif:
                        '8c85067116ddf1648cb63a5e01c191e1e874d8f8807d0eb6e479886ee204e4ae5bae1e64d46be01155d6080cb563b8da6659df33c0d2f111d320d00ed9ca5676',
                    stripeCustomerId: null,
                    role: 'CREATOR',
                    avatar: 'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/users/avatar/c8255a98-1795-408b-88cb-06620204455f-ambitious-puny-ice',
                    slug: 'maria-matveyeva',
                    wpSlug: 'wp-8ab039da-059f-41f6-9534-1887f071f22c',
                    deleted: false,
                    operator: false,
                    countryId: 'ckv7v4mtw0379hx129tdt8z83',
                    created: new Date(),
                    updated: new Date(),
                },
            },
        ],
        sponsors: [],
    },
    {
        id: 'clbq72o67235678g72kh1kmt8bj',
        name: 'Schoolboard Nr8',
        description:
            'This abstract artwork is a part of the SCIENCE ART collection by Anastasia Vasilyeva. The Semi-finalist of the international art contest organized by ARTBOX.Project Miami 2.0. \r\nThe painting was presented digitally from the 2nd-8th of December 2019 in Miami ART Weeks (during the famous Basel Art Show in Miami). It was published in several art magazines.\r\nIt\'s painted as a large square chalkboard with mathematical symbols and formulas.\r\nThe artist uses a multi-layer technique to make the color deeper.\r\nThis abstract painting could be also identified as an object, an old Schoolboard, which keeps old memories of our development path.\r\n\r\nMatt sprayed to protect the lettering on the canvas.\r\n\r\nAnastasia Vasilyeva for the interview at the exhibition in Madrid:\r\n"With my artworks, I want to touch the persons to remind us about something very personal.\r\nThe artworks from the Science art collection were made with a multi-layer technique, that I developed. It helps a base color to become a special depth effect. The lettering on this painting is an abstract element and helps to reach even more depth."',
        file: 'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/tokens/a2028d52-dcf6-45c2-b3de-8a02e8dfb0c5-gorgeous-vast-zebra.jpeg',
        previewFile: null,
        minimizedImage:
            'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/tokens/4fb29896-f36e-4d83-aef9-eb537f30b7c3-mini-purring-burly-river',
        s3Key: 'tokens/a2028d52-dcf6-45c2-b3de-8a02e8dfb0c5-gorgeous-vast-zebra.jpeg',
        previewS3Key: null,
        miniS3Key: 'tokens/4fb29896-f36e-4d83-aef9-eb537f30b7c3-mini-purring-burly-river',
        streamingId: null,
        slug: 'anastasia-schoolboard-nr8',
        currency: 'USD',
        hotChoice: true,
        tags: [],
        productStockId: 'clbq72o67235679g72k1qzzlqf0',
        tagId: null,
        price: 2600,
        status: 'APPROVED',
        remarks: '',
        disableDownload: false,
        soldout: false,
        published: true,
        deleted: false,
        created: new Date(),
        updated: new Date(),
        rights: [
            {
                id: 'clbq72o67235681g72kgo1m11dn',
                name: 'R001',
                productId: 'clbq72o67235678g72kh1kmt8bj',
                created: new Date(),
                updated: new Date(),
            },
        ],
        categories: [
            {
                id: 'clbvtcdmv420273g72k8rirh8by',
                productId: 'clbq72o67235678g72kh1kmt8bj',
                categoryId: 'ckv7v4np21713hx12brcv057e',
                created: new Date(),
                updated: new Date(),
                Category: {
                    id: 'ckv7v4np21713hx12brcv057e',
                    name: 'Art',
                    created: new Date(),
                    updated: new Date(),
                },
            },
        ],
        tag: null,
        stock: {
            id: 'clbq72o67235679g72k1qzzlqf0',
            stock: 1,
            lastNumber: 1,
            maxNumber: 1,
            created: new Date(),
            updated: new Date(),
        },
        views: {
            id: 'clbq72o7m235697g72kdqa6qljh',
            views: 15,
            productId: 'clbq72o67235678g72kh1kmt8bj',
            created: new Date(),
            updated: new Date(),
        },
        thumbnails: [],
        collections: [
            {
                id: 'clbq72quq235719g72kr9bw7wib',
                productId: 'clbq72o67235678g72kh1kmt8bj',
                userId: 'clbkpvemh921719qi2kk9sg6qog',
                tokenId: 'clbq72qtr235709g72ky75ov5f7',
                origin: true,
                created: new Date(),
                updated: new Date(),
                User: {
                    id: 'clbkpvemh921719qi2kk9sg6qog',
                    email: 'anavasilyeva@gmail.com',
                    sub: 'auth0|6397119dffa0ee78c0940d3f',
                    emailVerified: null,
                    firstName: 'Vasilyeva',
                    lastName: 'Anastasia',
                    nickname: 'Anastasia Vasilyeva',
                    password: null,
                    phone: '0791292124',
                    image: 'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/users/avatar/ccb5186c-563c-436a-ba06-7a5dd93cbf7c-shallow-boring-ocean',
                    s3Key: 'users/avatar/ccb5186c-563c-436a-ba06-7a5dd93cbf7c-shallow-boring-ocean',
                    biography:
                        'Anastasia Vasilyeva was born in 1982 in St.Petersburg (Russia) where she grew up. In 2008 she moved to Switzerland where she\'s been living since then. \r\n\r\nAnastasia Vasilyeva is an artist dedicated to abstract conceptual art. In her works, she combines art with motifs and themes of mathematics as well as computer science. Her work also focuses on current social problems. Inspired by Mark Rothko, Jackson Pollack, Kandinsky, and Gerhard Richter, Anastasia Vasilyeva makes a conceptual contribution to Contemporary Art. \r\n\r\nBorn in an artist-family (4th generation) she learned the basic painting techniques from her father and continued to further develop them in various painting courses. Anastasia is also very interested in the history of art. The art exhibitions of classical and modern works of art always give her new inputs and inspirations for her work.\r\n\r\nSince 2016 Anastasia Vasilyeva has been exhibiting her works in certain art galleries, museums as well as in large IT and insurance companies in the USA, Switzerland, Germany, and Estonia.\r\n2021 - Exhibition in Darwin Museum in Moscow, The project EARTH2021;\r\n2019 -Selected as Semi-finalist in the project MIAMI2.0 organized by ARTBOX.Projects. "School board N8" was presented in Wynwood during Art Basel Miami Week.\r\n2018 -The diptych "Glacier" was owned by the MUSEUM OF ART in Narva, Estonia;  \r\n\r\n\r\nInfluences\r\nMark Rothko, Jackson Pollack, Kandinsky, Gerhard Richter, Kazimir Malevich\r\n\r\n\r\nEducation\r\n2021-2021 MoMa Courses, specialization Modern and Contemporary Art and Design New York, New York, United States \r\n2016-2017 Mix media contemporary artist Sempach, Switzerland \r\n1999-2004 Dip. Applied Mathematician St.Petersburg, Russia ',
                    gender: 'FEMALE',
                    birthdate: new Date(),
                    sns: [
                        {
                            url: 'https://www.youtube.com/@AnastasiaVasilyeva',
                            name: 'youtube',
                        },
                        {
                            url: 'https://www.anavasilyeva.com/collections?isHome=1',
                            name: 'website',
                        },
                        {
                            url: 'https://www.instagram.com/anastasiavasiljeva/',
                            name: 'instagram',
                        },
                        {
                            url: 'https://twitter.com/VasilyevaArt',
                            name: 'twitter',
                        },
                    ],
                    hazamaAddress: 'hKwpAGMe5ybTJVWTRLRTCgyt7HFaV8odii',
                    hazamaWallet: null,
                    hazamaOriginalDomain: null,
                    salt: '8e9b30935d6f504a4c169385c0c445aa',
                    iv: 'b8b95e5859cca4263a3c06f9399861da',
                    encryptedWif:
                        '690edaf11c11b1d544373c759ac5ae82a6d5d3bd525607a5c3c6a6c25c5e34979d6b340395af0cd0b814b8d525d7046ba2c53896ca07b10eb69f42d47f587fbb',
                    stripeCustomerId: null,
                    role: 'CREATOR',
                    avatar: 'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/users/avatar/ccb5186c-563c-436a-ba06-7a5dd93cbf7c-shallow-boring-ocean',
                    slug: 'anastasia-vasilyeva',
                    wpSlug: 'wp-88af923f-83fd-4aa1-8042-0d6bd08a5daf',
                    deleted: false,
                    operator: false,
                    countryId: 'ckv7v4n761052hx128tpnfswx',
                    created: new Date(),
                    updated: new Date(),
                },
            },
        ],
        sponsors: [],
    },
    {
        id: 'clbp8ohc1169826g72kd11fhd9h',
        name: 'BUTTERFLY MATRIX RAINBOW',
        description:
            "Bright beautiful juicy rainbow butterfly! This is joyful decoration and wish fulfillment! This artwork is  a unique image. The same artwork can't be born twice. Collection of butterfly matrix is created with love and in a unique way.",
        file: 'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/tokens/28dd556e-7c3e-4034-a38a-6c82f1686226-abiding-salmon-farmer.jpeg',
        previewFile: null,
        minimizedImage:
            'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/tokens/634c8abc-b0b6-4166-94bb-ee92d3a289fb-mini-weak-mealy-horse',
        s3Key: 'tokens/28dd556e-7c3e-4034-a38a-6c82f1686226-abiding-salmon-farmer.jpeg',
        previewS3Key: null,
        miniS3Key: 'tokens/634c8abc-b0b6-4166-94bb-ee92d3a289fb-mini-weak-mealy-horse',
        streamingId: null,
        slug: 'butterfly-matrix-rainbow',
        currency: 'USD',
        hotChoice: true,
        tags: [],
        productStockId: 'clbp8ohc1169827g72kmjunfabr',
        tagId: null,
        price: 250,
        status: 'APPROVED',
        remarks: '',
        disableDownload: false,
        soldout: false,
        published: true,
        deleted: false,
        created: new Date(),
        updated: new Date(),
        rights: [
            {
                id: 'clbp8ohc1169829g72k08pra8zb',
                name: 'R001',
                productId: 'clbp8ohc1169826g72kd11fhd9h',
                created: new Date(),
                updated: new Date(),
            },
        ],
        categories: [
            {
                id: 'clbvtcdmv420273g72k8rirh8by',
                productId: 'clbp8ohc1169826g72kd11fhd9h',
                categoryId: 'ckv7v4np21713hx12brcv057e',
                created: new Date(),
                updated: new Date(),
                Category: {
                    id: 'ckv7v4np21713hx12brcv057e',
                    name: 'Art',
                    created: new Date(),
                    updated: new Date(),
                },
            },
        ],
        tag: null,
        stock: {
            id: 'clbp8ohc1169827g72kmjunfabr',
            stock: 1,
            lastNumber: 1,
            maxNumber: 1,
            created: new Date(),
            updated: new Date(),
        },
        views: {
            id: 'clbp8ohda169845g72kdqth8yi4',
            views: 14,
            productId: 'clbp8ohc1169826g72kd11fhd9h',
            created: new Date(),
            updated: new Date(),
        },
        thumbnails: [],
        collections: [
            {
                id: 'clbp8ojoi169867g72kmx1evvn1',
                productId: 'clbp8ohc1169826g72kd11fhd9h',
                userId: 'clblfb3fn963781qi2kxlvf4b3j',
                tokenId: 'clbp8ojnh169857g72kqj5kezx0',
                origin: true,
                created: new Date(),
                updated: new Date(),
                User: {
                    id: 'clblfb3fn963781qi2kxlvf4b3j',
                    email: 'elenashestakova3@gmail.com',
                    sub: 'auth0|6397b88031804ab92ff61643',
                    emailVerified: null,
                    firstName: 'HELEN ',
                    lastName: 'SHE ',
                    nickname: 'HELEN SHE',
                    password: null,
                    phone: '',
                    image: 'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/users/avatar/76d97446-eeb9-4b6e-8c9d-00b33fdb9c00-melted-moldy-elephant',
                    s3Key: 'users/avatar/76d97446-eeb9-4b6e-8c9d-00b33fdb9c00-melted-moldy-elephant',
                    biography:
                        "Every day look around me and create my own picture of the world! All my arts are individual and not repeatable. I draw with oil in my own pixel style. I am an art blogger. I have 10,000 followers on my YouTube channel, where I share my creativity with the world and teach to draw! Using different tools for creating pictures! I prefer to use 3-4 colors in the picture. My arts are my world, my soul, my knowledge. I am proud that, together with my husband Boris Shestakov, I participated in the exhibition of photographs, was my personal inspiration, and also co-authored an excellent photo work that was presented in the Hermitage.\r\n\r\n------\r\nABOUT HELEN SHE\r\nAn artist based in Italy whose paintings have been exhibited. She describes her artistic expression as being based on freedom of expression. She's distinctive abstractions are often inspired by her world travels. For her, each city or country is a new color, a new interpretation, and a new journey.",
                    gender: 'FEMALE',
                    birthdate: new Date(),
                    sns: [
                        {
                            url: 'https://www.youtube.com/@HelenShe',
                            name: 'youtube',
                        },
                        {
                            url: 'https://www.instagram.com/helensheofficial/',
                            name: 'instagram',
                        },
                        { url: 'https://helenshe.art/', name: 'website' },
                    ],
                    hazamaAddress: 'hJihqTZMk5VMegL38qdVGP71Y3Xjk147j2',
                    hazamaWallet: null,
                    hazamaOriginalDomain: null,
                    salt: '272aed0ad21cca8db4e6e63e801694a3',
                    iv: 'f5526a3038737cb85ec2e7029f99578b',
                    encryptedWif:
                        '6970c17c0d2e7d9bbd309f05032294bc9cb11472f623b2b012fd9958a9da2777dd5557d4426f891c123e0b1fd248813aaf13bbbb963014e34fda435c203688fe',
                    stripeCustomerId: null,
                    role: 'CREATOR',
                    avatar: 'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/users/avatar/76d97446-eeb9-4b6e-8c9d-00b33fdb9c00-melted-moldy-elephant',
                    slug: 'helen-she',
                    wpSlug: 'wp-ad9593f4-ba07-4965-bb9a-4cea467525c7',
                    deleted: false,
                    operator: false,
                    countryId: 'ckv7v4mrg0298hx12ni98w94r',
                    created: new Date(),
                    updated: new Date(),
                },
            },
        ],
        sponsors: [],
    },
    {
        id: 'clbn9l83059672ou12u3v3c6z2',
        name: 'Petals Whisper',
        description:
            'Floral composition with pink peonies.\r\nOriginal oil painting. Made with multilayered technique. You can see the painting in progress in additions images.\r\nPainted with brushes on the canvas. (100% Italian linen)\r\nThis work is unique, this is not a copy.',
        file: 'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/tokens/8b3cf454-08b5-44d9-82f6-794a52f0abf5-slimy-wet-bed.jpg',
        previewFile: null,
        minimizedImage:
            'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/tokens/d4136502-92ad-4a97-aa44-c00cf5ed211d-mini-hallowed-curved-easter',
        s3Key: 'tokens/8b3cf454-08b5-44d9-82f6-794a52f0abf5-slimy-wet-bed.jpg',
        previewS3Key: null,
        miniS3Key: 'tokens/d4136502-92ad-4a97-aa44-c00cf5ed211d-mini-hallowed-curved-easter',
        streamingId: null,
        slug: 'anechka-petals-whisper',
        currency: 'USD',
        hotChoice: true,
        tags: [],
        productStockId: 'clbn9l83059673ou12orzwwzr8',
        tagId: null,
        price: 500,
        status: 'APPROVED',
        remarks: '',
        disableDownload: false,
        soldout: false,
        published: true,
        deleted: false,
        created: new Date(),
        updated: new Date(),
        rights: [
            {
                id: 'clbn9l83059675ou12rvf35z18',
                name: 'R001',
                productId: 'clbn9l83059672ou12u3v3c6z2',
                created: new Date(),
                updated: new Date(),
            },
        ],
        categories: [
            {
                id: 'clbvtcdmv420273g72k8rirh8by',
                productId: 'clbn9l83059672ou12u3v3c6z2',
                categoryId: 'ckv7v4np21713hx12brcv057e',
                created: new Date(),
                updated: new Date(),
                Category: {
                    id: 'ckv7v4np21713hx12brcv057e',
                    name: 'Art',
                    created: new Date(),
                    updated: new Date(),
                },
            },
        ],
        tag: null,
        stock: {
            id: 'clbn9l83059673ou12orzwwzr8',
            stock: 1,
            lastNumber: 1,
            maxNumber: 1,
            created: new Date(),
            updated: new Date(),
        },
        views: {
            id: 'clbn9l83s59691ou121q88xyg5',
            views: 9,
            productId: 'clbn9l83059672ou12u3v3c6z2',
            created: new Date(),
            updated: new Date(),
        },
        thumbnails: [],
        collections: [
            {
                id: 'clbn9la0c59730ou121oqqqjuk',
                productId: 'clbn9l83059672ou12u3v3c6z2',
                userId: 'claolkgkr409545612kfepiin8f',
                tokenId: 'clbn9l9zq59720ou12o0hjc9mq',
                origin: true,
                created: new Date(),
                updated: new Date(),
                User: {
                    id: 'claolkgkr409545612kfepiin8f',
                    email: 'annamary62@gmail.com',
                    sub: 'auth0|63796f1b37456c9a6c374cac',
                    emailVerified: null,
                    firstName: 'Anna',
                    lastName: 'Reznikova',
                    nickname: 'Anechka',
                    password: null,
                    phone: '35799174944',
                    image: 'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/users/avatar/befa3f40-7209-4235-9aba-f84819c8870e-tangy-bent-mother',
                    s3Key: 'users/avatar/befa3f40-7209-4235-9aba-f84819c8870e-tangy-bent-mother',
                    biography:
                        'Anna Reznikova is a painter who lives in Cyprus and has exhibited in both solo and group events nationally. Her mostly figurative works feature subjects that excite and entrance her. She prefers to create using the mediums of watercolor and oil on canvas or paper.',
                    gender: 'FEMALE',
                    birthdate: new Date(),
                    sns: [
                        {
                            url: 'https://www.singulart.com/en/artist/anna-reznikova-11643',
                            name: 'website',
                        },
                    ],
                    hazamaAddress: 'ha4XKG7vJrG9FxAvroz7Rt1iBntnAJWCGP',
                    hazamaWallet: null,
                    hazamaOriginalDomain: null,
                    salt: 'b522e62c8cd6cba781d7357b8c641c14',
                    iv: '081f343d9014ac81e0dfa2492ea9bcbe',
                    encryptedWif:
                        'e7a133cd95cb491d1e78b4f6d1eda4ab09a78b494ee093c54ba749f92450c781b8aa1f001db9696558d347d7a74211f104912414bf41bc5bd24220f2bfd180dd',
                    stripeCustomerId: null,
                    role: 'CREATOR',
                    avatar: 'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/users/avatar/befa3f40-7209-4235-9aba-f84819c8870e-tangy-bent-mother',
                    slug: 'anechka',
                    wpSlug: 'wp-45b2bf42-5693-4cc3-83f4-f228f021e109',
                    deleted: false,
                    operator: false,
                    countryId: 'ckv7v4mpm0134hx12x8zps4r3',
                    created: new Date(),
                    updated: new Date(),
                },
            },
        ],
        sponsors: [],
    },
    {
        id: 'clbrf2abg282511g72k2icpjje5',
        name: 'Roses 5.',
        description:
            'Roses 5. Delicate rose bush: pink and white flowers on an abstract light abstract background, created with brushes and spatula, drops and splashes. The picture is filled with positive, solar energy, tenderness. Part of an ongoing series of flower arrangements. Expressionism. Impressionism. Used high quality materials. Acrylic painting on canvas. The sides are painted white.',
        file: 'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/tokens/ccbd1b46-5a3d-4d14-97e5-90f5269a7958-aggressive-sticky-keyboard.JPG',
        previewFile: null,
        minimizedImage:
            'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/tokens/98e1f9e3-9d40-4646-b85a-8151bbbd9ab9-mini-petite-yellow-quill',
        s3Key: 'tokens/ccbd1b46-5a3d-4d14-97e5-90f5269a7958-aggressive-sticky-keyboard.JPG',
        previewS3Key: null,
        miniS3Key: 'tokens/98e1f9e3-9d40-4646-b85a-8151bbbd9ab9-mini-petite-yellow-quill',
        streamingId: null,
        slug: 'iryna-roses5',
        currency: 'USD',
        hotChoice: true,
        tags: [],
        productStockId: 'clbrf2abg282512g72k05tvrytg',
        tagId: null,
        price: 935,
        status: 'APPROVED',
        remarks: '',
        disableDownload: false,
        soldout: false,
        published: true,
        deleted: false,
        created: new Date(),
        updated: new Date(),
        rights: [
            {
                id: 'clbrf2abg282514g72ktvzbc0o7',
                name: 'R001',
                productId: 'clbrf2abg282511g72k2icpjje5',
                created: new Date(),
                updated: new Date(),
            },
        ],
        categories: [
            {
                id: 'clbvtcdmv420273g72k8rirh8by',
                productId: 'clbrf2abg282511g72k2icpjje5',
                categoryId: 'ckv7v4np21713hx12brcv057e',
                created: new Date(),
                updated: new Date(),
                Category: {
                    id: 'ckv7v4np21713hx12brcv057e',
                    name: 'Art',
                    created: new Date(),
                    updated: new Date(),
                },
            },
        ],
        tag: null,
        stock: {
            id: 'clbrf2abg282512g72k05tvrytg',
            stock: 1,
            lastNumber: 1,
            maxNumber: 1,
            created: new Date(),
            updated: new Date(),
        },
        views: {
            id: 'clbrf2acp282530g72kbyjb3vv7',
            views: 17,
            productId: 'clbrf2abg282511g72k2icpjje5',
            created: new Date(),
            updated: new Date(),
        },
        thumbnails: [],
        collections: [
            {
                id: 'clbrf2e1f282552g72kyl2vo509',
                productId: 'clbrf2abg282511g72k2icpjje5',
                userId: 'cl9obg2yl269789712krsxvrb9a',
                tokenId: 'clbrf2e0f282542g72ky9164ii2',
                origin: true,
                created: new Date(),
                updated: new Date(),
                User: {
                    id: 'cl9obg2yl269789712krsxvrb9a',
                    email: 'irynakastsova@gmail.com',
                    sub: 'auth0|6357f5a4cad6defe4fb04aac',
                    emailVerified: null,
                    firstName: 'IRYNA',
                    lastName: 'KASTSOVA',
                    nickname: 'Irina Mask',
                    password: null,
                    phone: '+375293055697',
                    image: 'https://amatsuhi-prod-images.s3.amazonaws.com/users/avatar/3e749f0e-1d75-4639-9dc5-4d31493243f2-sparse-greasy-lunch',
                    s3Key: 'users/avatar/3e749f0e-1d75-4639-9dc5-4d31493243f2-sparse-greasy-lunch',
                    biography:
                        'Hello and welcome to my profile! \r\n\r\nBorn in 1976 in Poland. Warsaw. Graduated from the Art Belarusian Academy of Arts. Department: monumental and decorative painting. Then I worked in creative workshops. \r\n\r\nI paint in the style of realism, impressionism, pop art, expressionism. I love experiments in painting. An important place in my work is occupied by nature in all its manifestations. I strive to comprehend and reveal for myself and for the viewer the inner life of nature in all its diversity. At the same time, I really like to paint abstract paintings, when working on which the emotional aspect is crucial, and color is considered as an object. The visualization process is based on deliberate coincidence and precise development. In the center of the work are colors, light, structures and shapes that I use in a certain harmony with various techniques. I paint portraits to order from a photograph in the style of realism and pop art. I have been working with online galleries since 2020. \r\n\r\nI live and work in Poland. My paintings are full of life and joy, so... if you want, you can have a piece of this joy and happiness at home.',
                    gender: 'FEMALE',
                    birthdate: new Date(),
                    sns: [
                        {
                            url: 'https://www.facebook.com/media/set/?vanity=irynakastsova&set=a.2944054682407676',
                            name: 'facebook',
                        },
                        {
                            url: 'https://www.singulart.com/en/artist/iryna-kastsova-8217',
                            name: 'website',
                        },
                        {
                            url: 'https://twitter.com/ikastsova',
                            name: 'twitter',
                        },
                        {
                            url: 'https://www.instagram.com/irynakastsovaart/',
                            name: 'instagram',
                        },
                    ],
                    hazamaAddress: 'hFaZjr9Hs1t4UAx6pv9jEZDBq8ytHsEpXs',
                    hazamaWallet: null,
                    hazamaOriginalDomain: null,
                    salt: '2c8417e7d672801a213a9332c40a69ed',
                    iv: 'e55c89bd55e0f041c1fb78e1ebbe3cc6',
                    encryptedWif:
                        '6a8799361d9e5f3d4d3f59587f991b96ade06492cdbf402cdb81408b67408cc1f731bfbba8f58c676fdff8a1276f82f1f63ca1aa14aa6d2fdae6724efd1f9529',
                    stripeCustomerId: null,
                    role: 'CREATOR',
                    avatar: 'https://amatsuhi-prod-images.s3.amazonaws.com/users/avatar/3e749f0e-1d75-4639-9dc5-4d31493243f2-sparse-greasy-lunch',
                    slug: 'iryna',
                    wpSlug: 'wp-5e768aae-2c6d-48cf-8800-24f2bffc1851',
                    deleted: false,
                    operator: false,
                    countryId: 'ckv7v4n2i0806hx12rlrlg5bl',
                    created: new Date(),
                    updated: new Date(),
                },
            },
        ],
        sponsors: [],
    },
    {
        id: 'clbvtcdmv420270g72k0gyne8bs',
        name: 'Winter sketch Path to the river',
        description:
            'This painting is inspired by one winter day.\r\nSnowy footpath to the river. A beautiful landscape that pleases the eye.\r\nAll colors of the winter palette.\r\nFrom warm oranges to cool blues and turquoises.\r\nPasty painting.',
        file: 'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/tokens/bd62fea4-ca58-4e95-9f18-a7285440b8bf-spicy-fancy-sunset.JPG',
        previewFile: null,
        minimizedImage:
            'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/tokens/5e3b6e28-85d7-4c43-b39f-c043d39398d4-mini-putrid-teeny-plumber',
        s3Key: 'tokens/bd62fea4-ca58-4e95-9f18-a7285440b8bf-spicy-fancy-sunset.JPG',
        previewS3Key: null,
        miniS3Key: 'tokens/5e3b6e28-85d7-4c43-b39f-c043d39398d4-mini-putrid-teeny-plumber',
        streamingId: null,
        slug: 'winter-sketch-path-to-the-river',
        currency: 'USD',
        hotChoice: true,
        tags: [],
        productStockId: 'clbvtcdmv420271g72kksctlrsn',
        tagId: null,
        price: 270,
        status: 'APPROVED',
        remarks: '',
        disableDownload: false,
        soldout: false,
        published: true,
        deleted: false,
        created: new Date(),
        updated: new Date(),
        rights: [
            {
                id: 'clbvtcdmv420273g72k8rirh8by',
                name: 'R001',
                productId: 'clbvtcdmv420270g72k0gyne8bs',
                created: new Date(),
                updated: new Date(),
            },
        ],
        categories: [
            {
                id: 'clbvtcdmv420273g72k8rirh8by',
                productId: 'clbvtcdmv420270g72k0gyne8bs',
                categoryId: 'ckv7v4np21713hx12brcv057e',
                created: new Date(),
                updated: new Date(),
                Category: {
                    id: 'ckv7v4np21713hx12brcv057e',
                    name: 'Art',
                    created: new Date(),
                    updated: new Date(),
                },
            },
        ],
        tag: null,
        stock: {
            id: 'clbvtcdmv420271g72kksctlrsn',
            stock: 1,
            lastNumber: 1,
            maxNumber: 1,
            created: new Date(),
            updated: new Date(),
        },
        views: {
            id: 'clbvtcdo3420289g72ke4z8fsb6',
            views: 9,
            productId: 'clbvtcdmv420270g72k0gyne8bs',
            created: new Date(),
            updated: new Date(),
        },
        thumbnails: [],
        collections: [
            {
                id: 'clbvtcjbd420311g72k686yfvda',
                productId: 'clbvtcdmv420270g72k0gyne8bs',
                userId: 'claol3ims406132612ks0t1fkc7',
                tokenId: 'clbvtcjac420301g72knhud1x36',
                origin: true,
                created: new Date(),
                updated: new Date(),
                User: {
                    birthdate: new Date(),
                    id: 'claol3ims406132612ks0t1fkc7',
                    email: 'lukina.artist@gmail.com',
                    sub: 'auth0|63796c049740d5ecb0c8cfd3',
                    emailVerified: null,
                    firstName: 'Elena',
                    lastName: 'Lukina',
                    nickname: 'J.Lu',
                    password: null,
                    phone: '+37129513247',
                    image: 'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/users/avatar/b1245a15-8605-4b7b-9dfc-ed40d2ea52eb-burly-orange-baby',
                    s3Key: 'users/avatar/b1245a15-8605-4b7b-9dfc-ed40d2ea52eb-burly-orange-baby',
                    biography:
                        'Art for me is not only a way of expression, but also a source of joy and love! \r\n\r\nJ.Lu is a prizewinning artist from Latvia whose paintings have been exhibited in solo and group shows internationally. Inspired by the beauty of nature, Lukina creates impressionist style landscapes, botanical works, animal portraits, and more in oil on canvas. Her work is characterized by great technical skill and conjure up a warmth and nostalgia through soft color palettes and smooth textures.',
                    gender: 'FEMALE',
                    sns: [
                        {
                            url: 'https://www.singulart.com/en/artist/elena-lukina-8963',
                            name: 'website',
                        },
                        {
                            url: 'https://www.facebook.com/ArtElenaLukina/',
                            name: 'facebook',
                        },
                    ],
                    hazamaAddress: 'hMuABw4Y1buXQPaBURZYAsraQJrKZuPUib',
                    hazamaWallet: null,
                    hazamaOriginalDomain: null,
                    salt: '42bd99b0dd94348e4ae81b1b6156071e',
                    iv: '0c8c220ae4a9af48cf06193c7c0d8968',
                    encryptedWif:
                        '1d95c8094e914b8c058aff5c46323587c6a9ab1aa2ba767383422ff654b6ea67fe588746dfc59b1179efce4f1078bc7c07569bc4f49f512aa805c165f56b2137',
                    stripeCustomerId: null,
                    role: 'CREATOR',
                    avatar: 'https://amatsuhi-prod-images.s3.ap-northeast-1.amazonaws.com/users/avatar/b1245a15-8605-4b7b-9dfc-ed40d2ea52eb-burly-orange-baby',
                    slug: 'j-lu',
                    wpSlug: 'wp-51231ba1-5ff8-43a8-83c9-ca11a2f2a8fa',
                    deleted: false,
                    operator: false,
                    countryId: 'ckv7v4mtw0379hx129tdt8z83',
                    created: new Date(),
                    updated: new Date(),
                },
            },
        ],
        sponsors: [],
    },
];
